// Includes boss profiles and boss souls

var bossIcons = [
	// Boss profiles
	{ itemType: "boss", id: "alishar", name: "Alishar", imgUrl: "./public/images/boss/alishar.png" },
	{ itemType: "boss", id: "ani", name: "Ani", imgUrl: "./public/images/boss/ani.png" },
	{ itemType: "boss", id: "arkarium", name: "Arkarium", imgUrl: "./public/images/boss/arkarium.png", usedInSections: ["flames"] },
	{ itemType: "boss", id: "arkarium-sq", name: "Arkarium", imgUrl: "./public/images/boss/arkarium-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "balrog", name: "Balrog", imgUrl: "./public/images/boss/balrog.png" },
	{ itemType: "boss", id: "bamboo-warrior", name: "Bamboo Warrior", imgUrl: "./public/images/boss/bamboo-warrior.png" },
	{ itemType: "boss", id: "blackheart", name: "Blackheart", imgUrl: "./public/images/boss/blackheart.png" },
	{ itemType: "boss", id: "bm-1", name: "Aion of Creation, Yaldavaot of Destruction", imgUrl: "./public/images/boss/bm-1.png" },
	{ itemType: "boss", id: "bm-2", name: "Black Mage", imgUrl: "./public/images/boss/bm-2.png", usedInSections: ["flames", "potentials"] },
	{ itemType: "boss", id: "bm-3", name: "Black Mage", imgUrl: "./public/images/boss/bm-3.png" },
	{ itemType: "boss", id: "bm-4", name: "Black Mage", imgUrl: "./public/images/boss/bm-4.png" },
	{ itemType: "boss", id: "bm-sq", name: "Black Mage", imgUrl: "./public/images/boss/bm-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "captain-latanica", name: "Captain Latanica", imgUrl: "./public/images/boss/captain-latanica.png" },
	{ itemType: "boss", id: "chao", name: "Chao", imgUrl: "./public/images/boss/chao.png" },
	{ itemType: "boss", id: "chimera", name: "Chimera", imgUrl: "./public/images/boss/chimera.png" },
	{ itemType: "boss", id: "cowardly-lion", name: "Cowardly Lion", imgUrl: "./public/images/boss/cowardly-lion.png" },
	{ itemType: "boss", id: "cq57", name: "CQ57", imgUrl: "./public/images/boss/cq57.png" },
	{ itemType: "boss", id: "crimson-queen", name: "Crimson Queen", imgUrl: "./public/images/boss/crimson-queen.png" },
	{ itemType: "boss", id: "crimson-queen-sq", name: "Crimson Queen", imgUrl: "./public/images/boss/crimson-queen-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "cygnus", name: "Cygnus", imgUrl: "./public/images/boss/cygnus.png", usedInSections: ["flames"] },
	{ itemType: "boss", id: "cygnus-sq", name: "Cygnus", imgUrl: "./public/images/boss/cygnus-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "damien-1", name: "Damien", imgUrl: "./public/images/boss/damien-1.png", usedInSections: ["flames", "potentials"] },
	{ itemType: "boss", id: "damien-2", name: "Damien", imgUrl: "./public/images/boss/damien-2.png" },
	{ itemType: "boss", id: "damien-sq", name: "Damien", imgUrl: "./public/images/boss/damien-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "demon-king", name: "Demon King", imgUrl: "./public/images/boss/demon-king.png" },
	{ itemType: "boss", id: "deo", name: "Deo", imgUrl: "./public/images/boss/deo.png" },
	{ itemType: "boss", id: "dile", name: "Dile", imgUrl: "./public/images/boss/dile.png" },
	{ itemType: "boss", id: "djunkel", name: "Djunkel", imgUrl: "./public/images/boss/djunkel.png", usedInSections: ["flames", "potentials"] },
	{ itemType: "boss", id: "djunkel-sq", name: "Djunkel", imgUrl: "./public/images/boss/djunkel-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "dodo", name: "Dodo", imgUrl: "./public/images/boss/dodo.png" },
	{ itemType: "boss", id: "dorothy-1", name: "Dorothy", imgUrl: "./public/images/boss/dorothy-1.png" },
	{ itemType: "boss", id: "dorothy-2", name: "Dorothy", imgUrl: "./public/images/boss/dorothy-2.png" },
	{ itemType: "boss", id: "dragonoir", name: "Dorothy", imgUrl: "./public/images/boss/dragonoir.png" },
	{ itemType: "boss", id: "dragon-rider", name: "Dragon Rider", imgUrl: "./public/images/boss/dragon-rider.png" },
	{ itemType: "boss", id: "d-roy", name: "D.Roy", imgUrl: "./public/images/boss/d-roy.png" },
	{ itemType: "boss", id: "dusk", name: "Dusk", imgUrl: "./public/images/boss/dusk.png", usedInSections: ["flames", "potentials"] },
	{ itemType: "boss", id: "dusk-sq", name: "Dusk", imgUrl: "./public/images/boss/dusk-sq.png", usedInSections: ["boss-crystal"] },

	{ itemType: "boss", id: "eliza", name: "Eliza", imgUrl: "./public/images/boss/eliza.png" },
	{ itemType: "boss", id: "ephenia", name: "Ephenia", imgUrl: "./public/images/boss/ephenia.png" },
	{ itemType: "boss", id: "ergoth", name: "Ergoth", imgUrl: "./public/images/boss/ergoth.png" },
	{ itemType: "boss", id: "flame-wolf", name: "Flame Wolf", imgUrl: "./public/images/boss/flame-wolf.png" },
	{ itemType: "boss", id: "frankenroid-1", name: "Frankenroid", imgUrl: "./public/images/boss/frankenroid-1.png" },
	{ itemType: "boss", id: "frankenroid-2", name: "Frankenroid", imgUrl: "./public/images/boss/frankenroid-2.png" },
	{ itemType: "boss", id: "georg", name: "Georg", imgUrl: "./public/images/boss/georg.png" },
	{ itemType: "boss", id: "giant-spider", name: "Giant Spider", imgUrl: "./public/images/boss/giant-spider.png" },
	{ itemType: "boss", id: "griffey", name: "Griffey", imgUrl: "./public/images/boss/griffey.png" },
	{ itemType: "boss", id: "hawkeye", name: "Hawkeye", imgUrl: "./public/images/boss/hawkeye.png" },
	{ itemType: "boss", id: "hekaton", name: "Hekaton", imgUrl: "./public/images/boss/hekaton.png" },
	{ itemType: "boss", id: "heretic-hilla", name: "Heretic Hilla", imgUrl: "./public/images/boss/heretic-hilla.png", usedInSections: ["flames", "potentials"] },
	{ itemType: "boss", id: "heretic-hilla-sq", name: "Heretic Hilla", imgUrl: "./public/images/boss/heretic-hilla-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "hilla", name: "Hilla", imgUrl: "./public/images/boss/hilla.png", usedInSections: ["flames"] },
	{ itemType: "boss", id: "hilla-sq", name: "Hilla", imgUrl: "./public/images/boss/hilla-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "horntail", name: "Horntail", imgUrl: "./public/images/boss/horntail.png", usedInSections: ["flames"] },
	{ itemType: "boss", id: "horntail-sq", name: "Horntail", imgUrl: "./public/images/boss/horntail-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "ickhart", name: "Ickhart", imgUrl: "./public/images/boss/ickhart.png" },
	{ itemType: "boss", id: "irina", name: "Irina", imgUrl: "./public/images/boss/irina.png" },
	{ itemType: "boss", id: "jr-balrog", name: "Jr. Balrog", imgUrl: "./public/images/boss/jr-balrog.png" },
	{ itemType: "boss", id: "julieta-sq", name: "Julieta", imgUrl: "./public/images/boss/julieta-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "july", name: "July", imgUrl: "./public/images/boss/july.png" },

	{ itemType: "boss", id: "kariaine", name: "Kariaine", imgUrl: "./public/images/boss/kariaine.png" },
	{ itemType: "boss", id: "kawoong", name: "Kawoong", imgUrl: "./public/images/boss/kawoong.png", usedInSections: ["flames"] },
	{ itemType: "boss", id: "kawoong-sq", name: "Kwaoong", imgUrl: "./public/images/boss/kawoong-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "king-castle-golem", name: "King Castle Golem", imgUrl: "./public/images/boss/king-castle-golem.png" },
	{ itemType: "boss", id: "king-centipede", name: "King Centipede", imgUrl: "./public/images/boss/king-centipede.png" },
	{ itemType: "boss", id: "king-clang", name: "King Clang", imgUrl: "./public/images/boss/king-clang.png" },
	{ itemType: "boss", id: "king-mole", name: "King Mole", imgUrl: "./public/images/boss/king-mole.png" },
	{ itemType: "boss", id: "king-omen", name: "King Omen", imgUrl: "./public/images/boss/king-omen.png" },
	{ itemType: "boss", id: "king-sage-cat", name: "King Sage Cat", imgUrl: "./public/images/boss/king-sage-cat.png" },
	{ itemType: "boss", id: "king-slime", name: "King Slime", imgUrl: "./public/images/boss/king-slime.png" },
	{ itemType: "boss", id: "kumiho", name: "Kumiho", imgUrl: "./public/images/boss/kumiho.png" },
	{ itemType: "boss", id: "leviathan", name: "Leviathan", imgUrl: "./public/images/boss/leviathan.png" },
	{ itemType: "boss", id: "lilynouch", name: "Lilynouch", imgUrl: "./public/images/boss/lilynouch.png" },
	{ itemType: "boss", id: "lord-pirate", name: "Lord Pirate", imgUrl: "./public/images/boss/lord-pirate.png" },
	{ itemType: "boss", id: "lotus-1", name: "Lotus", imgUrl: "./public/images/boss/lotus-1.png" },
	{ itemType: "boss", id: "lotus-2", name: "Lotus", imgUrl: "./public/images/boss/lotus-2.png" },
	{ itemType: "boss", id: "lotus-3", name: "Lotus", imgUrl: "./public/images/boss/lotus-3.png", usedInSections: ["flames", "potentials"] },
	{ itemType: "boss", id: "lotus-sq", name: "Lotus", imgUrl: "./public/images/boss/lotus-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "lucid", name: "Lucid", imgUrl: "./public/images/boss/lucid.png", usedInSections: ["flames", "potentials"] },
	{ itemType: "boss", id: "lucid-sq", name: "Lucid", imgUrl: "./public/images/boss/lucid-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "lyka", name: "Lyka", imgUrl: "./public/images/boss/lyka.png" },
	{ itemType: "boss", id: "magnus-1", name: "Magnus", imgUrl: "./public/images/boss/magnus-1.png", usedInSections: ["flames", "star-force"] },
	{ itemType: "boss", id: "magnus-2", name: "Magnus", imgUrl: "./public/images/boss/magnus-2.png" },
	{ itemType: "boss", id: "magnus-sq", name: "Magnus", imgUrl: "./public/images/boss/magnus-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "mano", name: "Mano", imgUrl: "./public/images/boss/mano.png" },
	{ itemType: "boss", id: "manon", name: "Manon", imgUrl: "./public/images/boss/manon.png" },
	{ itemType: "boss", id: "mihile", name: "Mihile", imgUrl: "./public/images/boss/mihile.png" },
	{ itemType: "boss", id: "mokadin", name: "Mokadin", imgUrl: "./public/images/boss/mokadin.png" },
	{ itemType: "boss", id: "oz", name: "Oz", imgUrl: "./public/images/boss/oz.png" },

	{ itemType: "boss", id: "papa-pixie", name: "Papa Pixie", imgUrl: "./public/images/boss/papa-pixie.png" },
	{ itemType: "boss", id: "papulatus", name: "Papulatus", imgUrl: "./public/images/boss/papulatus.png" },
	{ itemType: "boss", id: "papulatus-sq", name: "Papulatus", imgUrl: "./public/images/boss/papulatus-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "pianus", name: "Pianus", imgUrl: "./public/images/boss/pianus.png" },
	{ itemType: "boss", id: "pierre-1", name: "Pierre", imgUrl: "./public/images/boss/pierre-1.png" },
	{ itemType: "boss", id: "pierre-2", name: "Pierre", imgUrl: "./public/images/boss/pierre-2.png" },
	{ itemType: "boss", id: "pierre-3", name: "Pierre", imgUrl: "./public/images/boss/pierre-3.png" },
	{ itemType: "boss", id: "pierre-sq", name: "Pierre", imgUrl: "./public/images/boss/pierre-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "pink-bean", name: "Pink Bean", imgUrl: "./public/images/boss/pink-bean.png", usedInSections: ["flames"] },
	{ itemType: "boss", id: "pink-bean-sq", name: "Pink Bean", imgUrl: "./public/images/boss/pink-bean-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "plaid", name: "Plaid", imgUrl: "./public/images/boss/plaid.png" },
	{ itemType: "boss", id: "pnou-sq", name: "Princess Nou", imgUrl: "./public/images/boss/pnou-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "poison-golem-1", name: "Poison Golem", imgUrl: "./public/images/boss/poison-golem-1.png" },
	{ itemType: "boss", id: "poison-golem-2", name: "Poison Golem", imgUrl: "./public/images/boss/poison-golem-2.png" },
	{ itemType: "boss", id: "poison-golem-3", name: "Poison Golem", imgUrl: "./public/images/boss/poison-golem-3.png" },
	{ itemType: "boss", id: "ranmaru-sq", name: "Ranmaru", imgUrl: "./public/images/boss/ranmaru-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "ravana", name: "Ravana", imgUrl: "./public/images/boss/ravana.png" },
	{ itemType: "boss", id: "reverse-dark-soul", name: "Reverse Dark Soul", imgUrl: "./public/images/boss/reverse-dark-soul.png" },
	{ itemType: "boss", id: "rex", name: "Rex", imgUrl: "./public/images/boss/rex.png" },
	{ itemType: "boss", id: "riche", name: "Riche", imgUrl: "./public/images/boss/riche.png" },
	{ itemType: "boss", id: "rock-spirit-1", name: "Rock Spirit", imgUrl: "./public/images/boss/rock-spirit-1.png" },
	{ itemType: "boss", id: "rock-spirit-2", name: "Rock Spirit", imgUrl: "./public/images/boss/rock-spirit-2.png" },
	{ itemType: "boss", id: "scarecrow", name: "Scarecrow", imgUrl: "./public/images/boss/scarecrow.png" },
	{ itemType: "boss", id: "seruf", name: "Seruf", imgUrl: "./public/images/boss/seruf.png" },
	{ itemType: "boss", id: "shinsoo", name: "Shinsoo", imgUrl: "./public/images/boss/shinsoo.png" },
	{ itemType: "boss", id: "snowman", name: "Snowman", imgUrl: "./public/images/boss/snowman.png" },
	{ itemType: "boss", id: "snow-witch", name: "Snow Witch", imgUrl: "./public/images/boss/snow-witch.png" },
	{ itemType: "boss", id: "stumpy", name: "Stumpy", imgUrl: "./public/images/boss/stumpy.png" },

	{ itemType: "boss", id: "tae-roon", name: "Tae Roon", imgUrl: "./public/images/boss/tae-roon.png" },
	{ itemType: "boss", id: "tarantulos", name: "Tarantulos", imgUrl: "./public/images/boss/tarantulos.png" },
	{ itemType: "boss", id: "timer", name: "Timer", imgUrl: "./public/images/boss/timer.png" },
	{ itemType: "boss", id: "tin-woodman", name: "Tin Woodman", imgUrl: "./public/images/boss/tin-woodman.png" },
	{ itemType: "boss", id: "toto", name: "Toto", imgUrl: "./public/images/boss/toto.png" },
	{ itemType: "boss", id: "transformed-stumpy", name: "Transformed Stumpy", imgUrl: "./public/images/boss/transformed-stumpy.png" },
	{ itemType: "boss", id: "treglow", name: "Treglow", imgUrl: "./public/images/boss/treglow.png" },
	{ itemType: "boss", id: "ursus", name: "Ursus", imgUrl: "./public/images/boss/ursus.png", usedInSections: ["spell-trace", "flames", "potentials"] },
	{ itemType: "boss", id: "velderoth", name: "Velderoth", imgUrl: "./public/images/boss/velderoth.png" },
	{ itemType: "boss", id: "vellum", name: "Vellum", imgUrl: "./public/images/boss/vellum.png", usedInSections: ["flames"] },
	{ itemType: "boss", id: "vellum-sq", name: "Vellum", imgUrl: "./public/images/boss/vellum-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "victor", name: "Victor", imgUrl: "./public/images/boss/victor.png" },
	{ itemType: "boss", id: "von-bon", name: "Von Bon", imgUrl: "./public/images/boss/vonbon.png" },
	{ itemType: "boss", id: "von-bon-sq", name: "Von Bon", imgUrl: "./public/images/boss/vonbon-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "von-leon", name: "Von Leon", imgUrl: "./public/images/boss/von-leon.png", usedInSections: ["flames"] },
	{ itemType: "boss", id: "von-leon-sq", name: "Von Leon", imgUrl: "./public/images/boss/von-leon-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "will-1", name: "Will", imgUrl: "./public/images/boss/will-1.png" },
	{ itemType: "boss", id: "will-2", name: "", imgUrl: "./public/images/boss/will-2.png" },
	{ itemType: "boss", id: "will-3", name: "Will", imgUrl: "./public/images/boss/will-3.png", usedInSections: ["flames", "potentials"] },
	{ itemType: "boss", id: "will-sq", name: "Will", imgUrl: "./public/images/boss/will-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "xerxes", name: "Xerxes", imgUrl: "./public/images/boss/xerxes.png" },
	{ itemType: "boss", id: "zakum", name: "Zakum", imgUrl: "./public/images/boss/zakum.png", usedInSections: ["flames"] },
	{ itemType: "boss", id: "zakum-sq", name: "Zakum", imgUrl: "./public/images/boss/zakum-sq.png", usedInSections: ["boss-crystal"] },
	{ itemType: "boss", id: "zeno", name: "Zeno", imgUrl: "./public/images/boss/zeno.png" },
	{ itemType: "boss", id: "zombie-mushmom", name: "Zombie Mushmom", imgUrl: "./public/images/boss/zombie-mushmom.png" },

	// Boss souls
	{ itemType: "boss-soul", id: "soul-cygnus", name: "Cygnus", imgUrl: "./public/images/souls/soul-cygnus.png" },
	{ itemType: "boss-soul", id: "soul-magnus", name: "Magnus", imgUrl: "./public/images/souls/soul-magnus.png", usedInSections: ["homepage", "todd"] },
	{ itemType: "boss-soul", id: "soul-lotus", name: "Lotus", imgUrl: "./public/images/souls/soul-lotus.png", usedInSections: ["soul-weapons"] },
	{ itemType: "boss-soul", id: "soul-lotus-aug", name: "Lotus (Augmented)", imgUrl: "./public/images/souls/soul-lotus-aug.png" },
	{ itemType: "boss-soul", id: "soul-damien", name: "Damien", imgUrl: "./public/images/souls/soul-damien.png" },
	{ itemType: "boss-soul", id: "soul-damien-aug", name: "Damien (Augmented)", imgUrl: "./public/images/souls/soul-damien-aug.png" },
	{ itemType: "boss-soul", id: "soul-queen", name: "Crimson Queen", imgUrl: "./public/images/souls/soul-queen.png" },
	{ itemType: "boss-soul", id: "soul-vellum", name: "Vellum", imgUrl: "./public/images/souls/soul-vellum.png" },
	{ itemType: "boss-soul", id: "soul-lucid", name: "Lucid", imgUrl: "./public/images/souls/soul-lucid.png" },
	{ itemType: "boss-soul", id: "soul-lucid-aug", name: "Lucid (Augmented)", imgUrl: "./public/images/souls/soul-lucid-aug.png" },
	{ itemType: "boss-soul", id: "soul-will", name: "Will", imgUrl: "./public/images/souls/soul-will.png" },
	{ itemType: "boss-soul", id: "soul-will-aug", name: "Will (Augmented)", imgUrl: "./public/images/souls/soul-will-aug.png" },
	{ itemType: "boss-soul", id: "soul-heretic-hilla", name: "Heretic Hilla", imgUrl: "./public/images/souls/soul-heretic-hilla.png" },
	{ itemType: "boss-soul", id: "soul-heretic-hilla-aug", name: "Heretic Hilla (Augmented)", imgUrl: "./public/images/souls/soul-heretic-hilla-aug.png" },
	{ itemType: "boss-soul", id: "soul-djunkel", name: "Djunkel", imgUrl: "./public/images/souls/soul-djunkel.png" },
	{ itemType: "boss-soul", id: "soul-djunkel-aug", name: "Djunkel (Augmented)", imgUrl: "./public/images/souls/soul-djunkel-aug.png" },
	{ itemType: "boss-soul", id: "soul-murrmurr", name: "Murrmurr", imgUrl: "./public/images/souls/soul-murrmurr.png" },
	{ itemType: "boss-soul", id: "soul-ursus", name: "Ursus", imgUrl: "./public/images/souls/soul-ursus.png" },
	{ itemType: "boss-soul", id: "soul-pink-bean", name: "Pink Bean", imgUrl: "./public/images/souls/soul-pink-bean.png" },
	{ itemType: "boss-soul", id: "soul-von-bon", name: "Von Bon", imgUrl: "./public/images/souls/soul-von-bon.png" },
	{ itemType: "boss-soul", id: "soul-pierre", name: "Pierre", imgUrl: "./public/images/souls/soul-pierre.png" },
	{ itemType: "boss-soul", id: "soul-arkarium", name: "Arkarium", imgUrl: "./public/images/souls/soul-arkarium.png" },
	{ itemType: "boss-soul", id: "soul-black-knight", name: "Black Knight Mokadin", imgUrl: "./public/images/souls/soul-black-knight.png" },
	{ itemType: "boss-soul", id: "soul-mad-mage", name: "Mad Mage Kariaine", imgUrl: "./public/images/souls/soul-mad-mage.png" },
	{ itemType: "boss-soul", id: "soul-vicious-hunter", name: "Vicious Hunter July", imgUrl: "./public/images/souls/soul-vicious-hunter.png" },
	{ itemType: "boss-soul", id: "soul-rampant-cyborg", name: "Rampant Cyborg CQ57", imgUrl: "./public/images/souls/soul-rampant-cyborg.png" },
	{ itemType: "boss-soul", id: "soul-bad-brawler", name: "Fighter Plaid", imgUrl: "./public/images/souls/soul-bad-brawler.png" },
	{ itemType: "boss-soul", id: "soul-hilla", name: "Hilla", imgUrl: "./public/images/souls/soul-hilla.png" },
	{ itemType: "boss-soul", id: "soul-von-leon", name: "Von Leon", imgUrl: "./public/images/souls/soul-von-leon.png" },
	{ itemType: "boss-soul", id: "soul-papulatus", name: "Papulatus", imgUrl: "./public/images/souls/soul-papulatus.png" },
	{ itemType: "boss-soul", id: "soul-papulatus-aug", name: "Papulatus (Augmented)", imgUrl: "./public/images/souls/soul-papulatus-aug.png" },
	{ itemType: "boss-soul", id: "soul-weight-of-soul", name: "Weight of Soul", imgUrl: "./public/images/souls/soul-weight-of-soul.png" },
	{ itemType: "boss-soul", id: "soul-weight-of-soul-aug", name: "Weight of Soul (Augmented)", imgUrl: "./public/images/souls/soul-weight-of-soul-aug.png" },
	{ itemType: "boss-soul", id: "soul-zakum", name: "Zakum", imgUrl: "./public/images/souls/soul-zakum.png" },
	{ itemType: "boss-soul", id: "soul-gold-dragon", name: "Gold Dragon", imgUrl: "./public/images/souls/soul-gold-dragon.png" },
	{ itemType: "boss-soul", id: "soul-red-tiger", name: "Red Tiger", imgUrl: "./public/images/souls/soul-red-tiger.png" },
	{ itemType: "boss-soul", id: "soul-balrog", name: "Balrog", imgUrl: "./public/images/souls/soul-balrog.png" },
	{ itemType: "boss-soul", id: "soul-nene", name: "Nene", imgUrl: "./public/images/souls/soul-nene.png" },
	{ itemType: "boss-soul", id: "soul-tutu", name: "Tutu", imgUrl: "./public/images/souls/soul-tutu.png" },
	{ itemType: "boss-soul", id: "soul-pig-bar", name: "Pig Bar", imgUrl: "./public/images/souls/soul-pig-bar.png" },
	{ itemType: "boss-soul", id: "soul-icafe", name: "Premium Internet Cafe", imgUrl: "./public/images/souls/soul-icafe.png" },
	{ itemType: "boss-soul", id: "soul-rock-spirit", name: "Spirit of Rock", imgUrl: "./public/images/souls/soul-rock-spirit.png" },
	{ itemType: "boss-soul", id: "soul-ephenia", name: "Ephenia", imgUrl: "./public/images/souls/soul-ephenia.png" },
	{ itemType: "boss-soul", id: "soul-ani", name: "Ani", imgUrl: "./public/images/souls/soul-ani.png" },
	{ itemType: "boss-soul", id: "soul-mu-gong", name: "Mu Gong", imgUrl: "./public/images/souls/soul-mu-gong.png" },
	{ itemType: "boss-soul", id: "soul-black-slime", name: "Black Slime", imgUrl: "./public/images/souls/soul-black-slime.png" },
	{ itemType: "boss-soul", id: "soul-xerxes", name: "Xerxes", imgUrl: "./public/images/souls/soul-xerxes.png" },
	{ itemType: "boss-soul", id: "soul-rex", name: "Rex", imgUrl: "./public/images/souls/soul-rex.png" },
	{ itemType: "boss-soul", id: "soul-pianus", name: "Pianus", imgUrl: "./public/images/souls/soul-pianus.png" },
	{ itemType: "boss-soul", id: "soul-dragon-rider", name: "Dragon Rider", imgUrl: "./public/images/souls/soul-dragon-rider.png" },
];

module.exports = bossIcons;