var equipTabIcons = [
	{ itemType: "equip", id: "golden-pickaxe", name: "Golden Pickaxe", imgUrl: "./public/images/equips/golden-pickaxe.png", usedInSections: ["spell-trace", "flames", "potentials"] },
	{ itemType: "equip", id: "golden-shovel", name: "Golden Shovel", imgUrl: "./public/images/equips/golden-shovel.png", usedInSections: ["spell-trace", "flames", "potentials"] },

	{ itemType: "equip", category: "android", id: "adamroid", name: "Beauty Adamroid", imgUrl: "./public/images/equips/android/adamroid.png" },
	{ itemType: "equip", category: "android", id: "aliciaroid", name: "Aliciaroid", imgUrl: "./public/images/equips/android/aliciaroid.png" },
	{ itemType: "equip", category: "android", id: "amberoid", name: "Beauty Amberoid", imgUrl: "./public/images/equips/android/amberoid.png" },
	{ itemType: "equip", category: "android", id: "android", name: "Android", imgUrl: "./public/images/equips/android/android.png" },
	{ itemType: "equip", category: "android", id: "broid", name: "Battle-Roid", imgUrl: "./public/images/equips/android/broid.png" },
	{ itemType: "equip", category: "android", id: "bronzeroid", name: "Beauty Bronzeroid", imgUrl: "./public/images/equips/android/bronzeroid.png" },
	{ itemType: "equip", category: "android", id: "chouxroid", name: "Chouxroid", imgUrl: "./public/images/equips/android/chouxroid.png" },
	{ itemType: "equip", category: "android", id: "cygnusroid", name: "Cygnusroid", imgUrl: "./public/images/equips/android/cygnusroid.png" },
	{ itemType: "equip", category: "android", id: "damienroid", name: "Damienroid", imgUrl: "./public/images/equips/android/damienroid.png" },
	{ itemType: "equip", category: "android", id: "everoid", name: "Beauty Everoid", imgUrl: "./public/images/equips/android/everoid.png" },
	{ itemType: "equip", category: "android", id: "gingeroid", name: "Beauty Gingeroid", imgUrl: "./public/images/equips/android/gingeroid.png" },
	{ itemType: "equip", category: "android", id: "hillaroid", name: "Heretic Hillaroid", imgUrl: "./public/images/equips/android/hillaroid.png" },
	{ itemType: "equip", category: "android", id: "ivoryroid", name: "Beauty Ivoryroid", imgUrl: "./public/images/equips/android/ivoryroid.png" },
	{ itemType: "equip", category: "android", id: "lucidroid", name: "Lucidroid", imgUrl: "./public/images/equips/android/lucidroid.png" },
	{ itemType: "equip", category: "android", id: "maroonroid", name: "Beauty Maroonroid", imgUrl: "./public/images/equips/android/maroonroid.png" },
	{ itemType: "equip", category: "android", id: "montblancroid", name: "Montblancroid", imgUrl: "./public/images/equips/android/montblancroid.png" },
	{ itemType: "equip", category: "android", id: "mugongroid", name: "Mu Gongroid", imgUrl: "./public/images/equips/android/mugongroid.png" },
	{ itemType: "equip", category: "android", id: "pieroid", name: "Pieroid", imgUrl: "./public/images/equips/android/pieroid.png" },
	{ itemType: "equip", category: "android", id: "puddingroid", name: "Puddingroid", imgUrl: "./public/images/equips/android/puddingroid.png" },
	{ itemType: "equip", category: "android", id: "scarletroid", name: "Beauty Scarletroid", imgUrl: "./public/images/equips/android/scarletroid.png" },
	{ itemType: "equip", category: "android", id: "silveroid", name: "Beauty Silveroid", imgUrl: "./public/images/equips/android/silveroid.png" },
	{ itemType: "equip", category: "android", id: "touperoid", name: "Beauty Touperoid", imgUrl: "./public/images/equips/android/touperoid.png" },
	{ itemType: "equip", category: "android", id: "willroid", name: "Willroid", imgUrl: "./public/images/equips/android/willroid.png" },

	{ itemType: "equip", category: "badge", id: "genesis-badge", name: "Badge in the Beginning", imgUrl: "./public/images/equips/badge/genesis-badge.png" },
	{ itemType: "equip", category: "badge", id: "hospital-director-badge", name: "Hospital Director's Badge", imgUrl: "./public/images/equips/badge/hospital-director-badge.png" },
	{ itemType: "equip", category: "badge", id: "lania-badge", name: "Lania's Triple Lunch Box", imgUrl: "./public/images/equips/badge/lania-box.png" },
	{ itemType: "equip", category: "badge", id: "lord-skull-badge", name: "Lord Skull Badge", imgUrl: "./public/images/equips/badge/lord-skull-badge.png" },
	{ itemType: "equip", category: "badge", id: "ventus-badge", name: "Crystal Ventus Badge", imgUrl: "./public/images/equips/badge/ventus-badge.png" },

	{ itemType: "equip", category: "belt", id: "angry-zakum-belt", name: "Angry Zakum Belt", imgUrl: "./public/images/equips/belt/angry-zakum-belt.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "belt", id: "ayame-belt", name: "Ayame's Treasure", imgUrl: "./public/images/equips/belt/ayame-belt.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "belt", id: "black-bean-belt", name: "Black Bean Belt", imgUrl: "./public/images/equips/belt/black-bean-belt.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "belt", id: "blue-buckle-belt", name: "Blue Buckle Belt", imgUrl: "./public/images/equips/belt/blue-buckle-belt.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "belt", id: "blue-gilded-belt", name: "Blue Gilded Belt", imgUrl: "./public/images/equips/belt/blue-gilded-belt.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "belt", id: "brown-buckle-belt", name: "Brown Buckle Belt", imgUrl: "./public/images/equips/belt/brown-buckle-belt.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "belt", id: "elite-heliseum-belt", name: "Elite Heliseum Belt", imgUrl: "./public/images/equips/belt/elite-heliseum-belt.png", usedInSections: ["star-force"] },
	{ itemType: "equip", category: "belt", id: "exquisite-belt", name: "Exquisite Belt", imgUrl: "./public/images/equips/belt/exquisite-belt.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "belt", id: "fantasy-belt", name: "Fantasy Belt", imgUrl: "./public/images/equips/belt/fantasy-belt.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "belt", id: "golden-clover-belt", name: "Golden Clover Belt", imgUrl: "./public/images/equips/belt/golden-clover-belt.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "belt", id: "green-buckle-belt", name: "Green Buckle Belt", imgUrl: "./public/images/equips/belt/green-buckle-belt.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "belt", id: "maple-treasure-belt", name: "Maple Treasure Belt", imgUrl: "./public/images/equips/belt/maple-treasure-belt.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "belt", id: "nova-belt", name: "Nova Belt", imgUrl: "./public/images/equips/belt/nova-belt.png", usedInSections: ["star-force"] },
	{ itemType: "equip", category: "belt", id: "purple-gilded-belt", name: "Purple Gilded Belt", imgUrl: "./public/images/equips/belt/purple-gilded-belt.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "belt", id: "red-gilded-belt", name: "Red Gilded Belt", imgUrl: "./public/images/equips/belt/red-gilded-belt.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "belt", id: "rising-sun-belt", name: "Rising Sun Belt", imgUrl: "./public/images/equips/belt/rising-sun-belt.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "belt", id: "season-2-belt", name: "Season 2 Belt", imgUrl: "./public/images/equips/belt/season-2-belt.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "belt", id: "tyrant-belt", name: "Tyrant Belt", imgUrl: "./public/images/equips/belt/tyrant-belt.png", usedInSections: ["star-force"] },
	
	{ itemType: "equip", category: "bottom", id: "faf-archer-bottom", name: "Trickster Ranger Pants", imgUrl: "./public/images/equips/bottom/faf-archer-bottom.png" },
	{ itemType: "equip", category: "bottom", id: "faf-mage-bottom", name: "Trickster Dunwitch Pants", imgUrl: "./public/images/equips/bottom/faf-mage-bottom.png" },
	{ itemType: "equip", category: "bottom", id: "faf-pirate-bottom", name: "Trickster Wanderer Pants", imgUrl: "./public/images/equips/bottom/faf-pirate-bottom.png" },
	{ itemType: "equip", category: "bottom", id: "faf-thief-bottom", name: "Trickster Assassin Pants", imgUrl: "./public/images/equips/bottom/faf-thief-bottom.png" },
	{ itemType: "equip", category: "bottom", id: "faf-warrior-bottom", name: "Trickster Warrior Pants", imgUrl: "./public/images/equips/bottom/faf-warrior-bottom.png", usedInSections: ["todd-sequence"] },

	{ itemType: "equip", category: "cape", id: "10th-anniv-cape", name: "10th Anniversary Saint Cape", imgUrl: "./public/images/equips/cape/10th-anniv-cape.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "cape", id: "abs-cape", name: "Absolabs Cape", imgUrl: "./public/images/equips/cape/abs-cape.png", usedInSections: ["flames", "todd-sequence"] },
	{ itemType: "equip", category: "cape", id: "acs-cape", name: "Arcaneshade Cape", imgUrl: "./public/images/equips/cape/acs-cape.png", usedInSections: ["star-force", "todd-sequence"] },
	{ itemType: "equip", category: "cape", id: "angry-zakum-cape", name: "Angry Zakum Cape", imgUrl: "./public/images/equips/cape/angry-zakum-cape.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "cape", id: "black-cape", name: "Black Cape", imgUrl: "./public/images/equips/cape/black-cape.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "cape", id: "elite-heliseum-cape", name: "Elite Heliseum Cape", imgUrl: "./public/images/equips/cape/elite-heliseum-cape.png", usedInSections: ["star-force"] },
	{ itemType: "equip", category: "cape", id: "empress-warrior-cape", name: "Lion Heart Battle Cape", imgUrl: "./public/images/equips/cape/empress-warrior-cape.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "cape", id: "fensalir-cape", name: "Fensalir Cape", imgUrl: "./public/images/equips/cape/fensalir-cape.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "cape", id: "ludibrium-cape", name: "Ludibrium Cape", imgUrl: "./public/images/equips/cape/ludibrium-cape.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "cape", id: "maple-treasure-cape", name: "Maple Treasure Cape", imgUrl: "./public/images/equips/cape/maple-treasure-cape.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "cape", id: "nova-cape", name: "Nova Cape", imgUrl: "./public/images/equips/cape/nova-cape.png", usedInSections: ["star-force"] },
	{ itemType: "equip", category: "cape", id: "rvl-cape", name: "Royal Von Leon Cape", imgUrl: "./public/images/equips/cape/rvl-cape.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "cape", id: "timeless-moonlight", name: "Timeless Moonlight", imgUrl: "./public/images/equips/cape/timeless-moonlight.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "cape", id: "tyrant-cape", name: "Tyrant Cape", imgUrl: "./public/images/equips/cape/tyrant-cape.png", usedInSections: ["star-force"] },

	{ itemType: "equip", category: "earring", id: "blue-moon", name: "Blue Moon", imgUrl: "./public/images/equips/earring/blue-moon.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "commander-force-earrings", name: "Commander Force Earrings", imgUrl: "./public/images/equips/earring/commander-force-earrings.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "dea-sidus", name: "Dea Sidus Earrings", imgUrl: "./public/images/equips/earring/dea-sidus.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "half-earrings", name: "Half Earrings", imgUrl: "./public/images/equips/earring/half-earrings.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "ifia-earrings", name: "Ifia's Earrings", imgUrl: "./public/images/equips/earring/ifia-earrings.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "inverse-jewel-earrings", name: "Inverse Jewel Earrings", imgUrl: "./public/images/equips/earring/inverse-jewel-earrings.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "meister-studs", name: "Meister Ear Studs", imgUrl: "./public/images/equips/earring/meister-studs.png", usedInSections: ["flames", "todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "metal-heart-earrings", name: "Metal Heart Earrings", imgUrl: "./public/images/equips/earring/metal-heart-earrings.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "metal-silver-earrings", name: "Metal Silver Earrings", imgUrl: "./public/images/equips/earring/metal-silver-earrings.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "ocean-glow-earrings", name: "Ocean Glow Earrings", imgUrl: "./public/images/equips/earring/ocean-glow-earrings.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "octopus-earrings", name: "Octopus Earrings", imgUrl: "./public/images/equips/earring/octopus-earrings.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "pink-flower-earrings", name: "Pink Flower Earrings", imgUrl: "./public/images/equips/earring/pink-flower-earrings.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "rose-earrings", name: "Rose Earrings", imgUrl: "./public/images/equips/earring/rose-earrings.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "scarlet-earrings", name: "Scarlet Earrings", imgUrl: "./public/images/equips/earring/scarlet-earrings.png", usedInSections: ["set-effects"] },
	{ itemType: "equip", category: "earring", id: "shield-earrings", name: "Shield Earrings", imgUrl: "./public/images/equips/earring/shield-earrings.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "skull-earrings", name: "Skull Earrings", imgUrl: "./public/images/equips/earring/skull-earrings.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "strawberry-earrings", name: "Strawberry Earrings", imgUrl: "./public/images/equips/earring/strawberry-earrings.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "sword-earrings", name: "Sword Earrings", imgUrl: "./public/images/equips/earring/sword-earrings.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "earring", id: "will-o-the-wisps", name: "Will o' the Wisps", imgUrl: "./public/images/equips/earring/will-o-the-wisps.png", usedInSections: ["todd-sequence"] },
	
	{ itemType: "equip", category: "emblem", id: "angel-emblem", name: "Angel Emblem (Angelic Buster)", imgUrl: "./public/images/equips/emblem/angel-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "dragon-emblem", name: "Dragon Emblem (Kaiser)", imgUrl: "./public/images/equips/emblem/dragon-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "eternal-time-emblem", name: "Eternal Time Emblem (Zero)", imgUrl: "./public/images/equips/emblem/eternal-time-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-abyss-emblem", name: "Gold Abyss Emblem (Ark)", imgUrl: "./public/images/equips/emblem/gold-abyss-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-agent-emblem", name: "Gold Agent Emblem (Cadena)", imgUrl: "./public/images/equips/emblem/gold-agent-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-aran-emblem", name: "Gold Heroic Emblem (Aran)", imgUrl: "./public/images/equips/emblem/gold-aran-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-blossom-emblem", name: "Gold Blossom Emblem (Kanna)", imgUrl: "./public/images/equips/emblem/gold-blossom-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-crescent-emblem", name: "Gold Crescent Emblem (Hayato)", imgUrl: "./public/images/equips/emblem/gold-crescent-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-crystal-emblem", name: "Gold Crystal Emblem (Illium)", imgUrl: "./public/images/equips/emblem/gold-crystal-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-cygnus-emblem", name: "Gold Cygnus Emblem (Cygnus Knights)", imgUrl: "./public/images/equips/emblem/gold-cygnus-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-demon-emblem", name: "Gold Demon Emblem (Demon)", imgUrl: "./public/images/equips/emblem/gold-demon-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-dragon-emblem", name: "Gold Dragon Emblem (Zen)", imgUrl: "./public/images/equips/emblem/gold-dragon-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-eunwol-emblem", name: "Gold Heroic Emblem (Eunwol)", imgUrl: "./public/images/equips/emblem/gold-eunwol-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-evan-emblem", name: "Gold Heroic Emblem (Evan)", imgUrl: "./public/images/equips/emblem/gold-evan-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-heh-emblem", name: "Gold Heaven, Earth and Human Emblem (Ho Young)", imgUrl: "./public/images/equips/emblem/gold-heh-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-kinesis-emblem", name: "Gold Kinesis Emblem (Kinesis)", imgUrl: "./public/images/equips/emblem/gold-kinesis-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-knight-emblem", name: "Gold Knight Emblem (Adele)", imgUrl: "./public/images/equips/emblem/gold-knight-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-lumi-emblem", name: "Gold Heroic Emblem (Luminous)", imgUrl: "./public/images/equips/emblem/gold-lumi-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-maple-leaf-emblem", name: "Gold Maple Leaf Emblem", imgUrl: "./public/images/equips/emblem/gold-maple-leaf-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-merc-emblem", name: "Gold Heroic Emblem (Mercedes)", imgUrl: "./public/images/equips/emblem/gold-merc-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-phantom-emblem", name: "Gold Heroic Emblem (Phantom)", imgUrl: "./public/images/equips/emblem/gold-phantom-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "gold-resistance-emblem", name: "Gold Resistance Emblem", imgUrl: "./public/images/equips/emblem/gold-resistance-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "seed-expert-emblem", name: "The Seed Expert Emblem", imgUrl: "./public/images/equips/emblem/seed-expert-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "seed-legend-emblem", name: "The Seed Legend Emblem", imgUrl: "./public/images/equips/emblem/seed-legend-emblem.png" },
	{ itemType: "equip", category: "emblem", id: "seed-master-emblem", name: "The Seed Master Emblem", imgUrl: "./public/images/equips/emblem/seed-master-emblem.png" },
	
	{ itemType: "equip", category: "eye-acc", id: "aqua-letter", name: "Aqua Letter Eye Decoration", imgUrl: "./public/images/equips/eye/aqua-letter.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "eye-acc", id: "black-bean-mark", name: "Black Bean Mark", imgUrl: "./public/images/equips/eye/black-bean-mark.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "eye-acc", id: "damien-eye", name: "Magical Eye Patch", imgUrl: "./public/images/equips/eye/damien-eye.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "eye-acc", id: "kenta-new-goggles", name: "Kenta's New Goggles", imgUrl: "./public/images/equips/eye/kenta-new-goggles.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "eye-acc", id: "michaela-new-glasses", name: "Michaela's New Glasses", imgUrl: "./public/images/equips/eye/michaela-new-glasses.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "eye-acc", id: "michael-new-glasses", name: "Michael's New Glasses", imgUrl: "./public/images/equips/eye/michael-new-glasses.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "eye-acc", id: "mystic-eye", name: "Mystic Eye Accessory", imgUrl: "./public/images/equips/eye/mystic-eye.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "eye-acc", id: "papulatus-mark", name: "Papulatus Mark", imgUrl: "./public/images/equips/eye/papulatus-mark.png", usedInSections: ["flames", "todd-sequence"] },

	{ itemType: "equip", category: "face-acc", id: "condensed-crystal", name: "Condensed Strength Crystalline", imgUrl: "./public/images/equips/face/condensed-crystal.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "face-acc", id: "dazzling-golden-image", name: "Dazzling Golden Image", imgUrl: "./public/images/equips/face/dazzling-golden-image.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "face-acc", id: "frontier-b-chicle", name: "Frontier B Black Chicle", imgUrl: "./public/images/equips/face/frontier-b-chicle.png" },
	{ itemType: "equip", category: "face-acc", id: "frontier-c-chicle", name: "Frontier C White Chicle", imgUrl: "./public/images/equips/face/frontier-c-chicle.png" },
	{ itemType: "equip", category: "face-acc", id: "lotus-mark", name: "Loose Control Machine Mark", imgUrl: "./public/images/equips/face/lotus-mark.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "face-acc", id: "meister-symbol", name: "Shiny Red Meister Symbol", imgUrl: "./public/images/equips/face/meister-symbol.png", usedInSections: ["flames", "todd-sequence"] },

	{ itemType: "equip", category: "gloves", id: "abs-gloves", name: "Absolabs Gloves", imgUrl: "./public/images/equips/gloves/abs-glove.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "gloves", id: "acs-gloves", name: "Arcaneshade Gloves", imgUrl: "./public/images/equips/gloves/acs-glove.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "gloves", id: "antique-root-mitts", name: "Antique Root Mitts", imgUrl: "./public/images/equips/gloves/antique-root-mitts.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "gloves", id: "eclectic-warrior-gloves", name: "Eclectic Bergamot", imgUrl: "./public/images/equips/gloves/eclectic-warrior-glove.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "gloves", id: "empress-warrior-gloves", name: "Lion Heart Battle Bracers", imgUrl: "./public/images/equips/gloves/empress-warrior-glove.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "gloves", id: "expert-apprentice-gloves", name: "Expert Apprentice's Gloves", imgUrl: "./public/images/equips/gloves/expert-apprentice-gloves.png" },
	{ itemType: "equip", category: "gloves", id: "expert-gloves", name: "Expert's Gloves", imgUrl: "./public/images/equips/gloves/expert-gloves.png" },
	{ itemType: "equip", category: "gloves", id: "fensalir-gloves", name: "Fensalir Gloves", imgUrl: "./public/images/equips/gloves/fens-glove.png", usedInSections: ["flames", "todd-sequence"] },
	{ itemType: "equip", category: "gloves", id: "hero-gloves", name: "Hero's Gloves", imgUrl: "./public/images/equips/gloves/hero-gloves.png", usedInSections: ["set-effects"] },
	{ itemType: "equip", category: "gloves", id: "mu-gong-gloves", name: "Mu Gong's Gloves", imgUrl: "./public/images/equips/gloves/mu-gong-gloves.png" },
	{ itemType: "equip", category: "gloves", id: "muspell-gloves", name: "Muspell Gloves", imgUrl: "./public/images/equips/gloves/muspell-glove.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "gloves", id: "necro-gloves", name: "Necro Gloves", imgUrl: "./public/images/equips/gloves/necro-glove.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "gloves", id: "rvl-gloves", name: "Royal Von Leon Gloves", imgUrl: "./public/images/equips/gloves/rvl-glove.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "gloves", id: "so-gong-gloves", name: "So Gong's Gloves", imgUrl: "./public/images/equips/gloves/so-gong-gloves.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "gloves", id: "tyrant-gloves", name: "Tyrant Gloves", imgUrl: "./public/images/equips/gloves/tyrant-gloves.png", usedInSections: ["star-force"] },
	
	{ itemType: "equip", category: "hat", id: "abs-archer-hat", name: "Absolabs Trueshot Hood", imgUrl: "./public/images/equips/hat/abs-archer-hat.png" },
	{ itemType: "equip", category: "hat", id: "abs-mage-hat", name: "Absolabs Cabalist Crown", imgUrl: "./public/images/equips/hat/abs-mage-hat.png" },
	{ itemType: "equip", category: "hat", id: "abs-pirate-hat", name: "Absolabs Brigadier Fedora", imgUrl: "./public/images/equips/hat/abs-pirate-hat.png" },
	{ itemType: "equip", category: "hat", id: "abs-thief-hat", name: "Absolabs Shadow Beret", imgUrl: "./public/images/equips/hat/abs-thief-hat.png" },
	{ itemType: "equip", category: "hat", id: "abs-warrior-hat", name: "Absolabs Bastion Helm", imgUrl: "./public/images/equips/hat/abs-warrior-hat.png" },	
	{ itemType: "equip", category: "hat", id: "acs-archer-hat", name: "Arcaneshade Archer Hat", imgUrl: "./public/images/equips/hat/acs-archer-hat.png" },
	{ itemType: "equip", category: "hat", id: "acs-mage-hat", name: "Arcaneshade Mage Hat", imgUrl: "./public/images/equips/hat/acs-mage-hat.png" },
	{ itemType: "equip", category: "hat", id: "acs-pirate-hat", name: "Arcaneshade Pirate Hat", imgUrl: "./public/images/equips/hat/acs-pirate-hat.png" },
	{ itemType: "equip", category: "hat", id: "acs-thief-hat", name: "Arcaneshade Bandit Hat", imgUrl: "./public/images/equips/hat/acs-thief-hat.png" },
	{ itemType: "equip", category: "hat", id: "acs-warrior-hat", name: "Arcaneshade Knight Hat", imgUrl: "./public/images/equips/hat/acs-warrior-hat.png", usedInSections: ["flames"] },
	{ itemType: "equip", category: "hat", id: "faf-archer-hat", name: "Highness Ranger Beret", imgUrl: "./public/images/equips/hat/faf-archer-hat.png" },
	{ itemType: "equip", category: "hat", id: "faf-mage-hat", name: "Highness Dunwitch Hat", imgUrl: "./public/images/equips/hat/faf-mage-hat.png" },
	{ itemType: "equip", category: "hat", id: "faf-pirate-hat", name: "Highness Wanderer Hat", imgUrl: "./public/images/equips/hat/faf-pirate-hat.png" },
	{ itemType: "equip", category: "hat", id: "faf-thief-hat", name: "Highness Assassin Bonnet", imgUrl: "./public/images/equips/hat/faf-thief-hat.png" },
	{ itemType: "equip", category: "hat", id: "faf-warrior-hat", name: "Highness Warrior Helm", imgUrl: "./public/images/equips/hat/faf-warrior-hat.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "hat", id: "chaos-vellum-hat", name: "Chaos Vellum Helm", imgUrl: "./public/images/equips/hat/chaos-vellum.png", usedInSections: ["homepage", "flames", "set-effects"] },
	
	{ itemType: "equip", category: "heart", id: "beautyroid-heart", name: "Sincere Beautyroid Heart", imgUrl: "./public/images/equips/heart/beautyroid-heart.png" },
	{ itemType: "equip", category: "heart", id: "black-heart", name: "Black Heart", imgUrl: "./public/images/equips/heart/black-heart.png" },
	{ itemType: "equip", category: "heart", id: "liquid-metal-heart", name: "Liquid Metal Heart", imgUrl: "./public/images/equips/heart/liquid-metal-heart.png" },
	{ itemType: "equip", category: "heart", id: "outlaw-heart", name: "Outlaw Heart", imgUrl: "./public/images/equips/heart/outlaw-heart.png" },
	{ itemType: "equip", category: "heart", id: "titanium-heart", name: "Titanium Heart", imgUrl: "./public/images/equips/heart/titanium-heart.png" },

	{ itemType: "equip", category: "medal", id: "chef-medal", name: "Absolute Palate Legendary Grade Medal", imgUrl: "./public/images/equips/medal/chef-medal.png" },
	{ itemType: "equip", category: "medal", id: "monster-park-medal", name: "Seven-day Monster Parker", imgUrl: "./public/images/equips/medal/monster-park-medal.png" },
	
	{ itemType: "equip", category: "overall", id: "abs-archer-overall", name: "Absolabs Trueshot Coat", imgUrl: "./public/images/equips/overall/abs-archer-overall.png" },
	{ itemType: "equip", category: "overall", id: "abs-mage-overall", name: "Absolabs Cabalist Gown", imgUrl: "./public/images/equips/overall/abs-mage-overall.png" },
	{ itemType: "equip", category: "overall", id: "abs-pirate-overall", name: "Absolabs Brigadier Cuirass", imgUrl: "./public/images/equips/overall/abs-pirate-overall.png" },
	{ itemType: "equip", category: "overall", id: "abs-thief-overall", name: "Absolabs Shadow Suit", imgUrl: "./public/images/equips/overall/abs-thief-overall.png" },
	{ itemType: "equip", category: "overall", id: "abs-warrior-overall", name: "Absolabs Bastion Hauberk", imgUrl: "./public/images/equips/overall/abs-warrior-overall.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "overall", id: "acs-archer-overall", name: "Arcaneshade Archer Suit", imgUrl: "./public/images/equips/overall/acs-archer-suit.png" },
	{ itemType: "equip", category: "overall", id: "acs-mage-overall", name: "Arcaneshade Mage Suit", imgUrl: "./public/images/equips/overall/acs-mage-suit.png" },
	{ itemType: "equip", category: "overall", id: "acs-pirate-overall", name: "Arcaneshade Pirate Suit", imgUrl: "./public/images/equips/overall/acs-pirate-suit.png" },
	{ itemType: "equip", category: "overall", id: "acs-thief-overall", name: "Arcaneshade Bandit Suit", imgUrl: "./public/images/equips/overall/acs-thief-suit.png" },
	{ itemType: "equip", category: "overall", id: "acs-warrior-overall", name: "Arcaneshade Knight Suit", imgUrl: "./public/images/equips/overall/acs-warrior-suit.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "overall", id: "eclectic-warrior-suit", name: "Eclectic Taragon", imgUrl: "./public/images/equips/overall/eclectic-warrior-suit.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "overall", id: "empress-warrior-suit", name: "Lion Heart Battle Mail", imgUrl: "./public/images/equips/overall/empress-warrior-suit.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "overall", id: "fensalir-warrior-suit", name: "Fensalir Cronus Mail", imgUrl: "./public/images/equips/overall/fensalir-warrior-suit.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "overall", id: "muspell-warrior-suit", name: "Muspell Warlord Suit", imgUrl: "./public/images/equips/overall/muspell-warrior-suit.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "overall", id: "necro-warrior-suit", name: "Necro Warrior Suit", imgUrl: "./public/images/equips/overall/necro-warrior-suit.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "overall", id: "rvl-warrior-suit", name: "Royal Von Leon Gladiator Suit", imgUrl: "./public/images/equips/overall/rvl-warrior-suit.png", usedInSections: ["todd-sequence"] },

	{ itemType: "equip", category: "pendant", id: "cht-pendant", name: "Chaos Horntail Necklace", imgUrl: "./public/images/equips/pendant/cht-pendant.png", usedInSections: ["flames", "todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "dom-pendant", name: "Dominator Pendant", imgUrl: "./public/images/equips/pendant/dom-pendant.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "frontier-b-pendant", name: "Frontier B Black Pendant", imgUrl: "./public/images/equips/pendant/frontier-b-pendant.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "frontier-c-pendant", name: "Frontier C White Pendant", imgUrl: "./public/images/equips/pendant/frontier-c-pendant.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "greed-pendant", name: "Greed Pendant", imgUrl: "./public/images/equips/pendant/greed-pendant.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "green-pendant", name: "Green Pendant", imgUrl: "./public/images/equips/pendant/green-pendant.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "hilla-pendant", name: "Source of Pain", imgUrl: "./public/images/equips/pendant/hilla-pendant.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "ht-pendant", name: "Horned Tail Necklace", imgUrl: "./public/images/equips/pendant/ht-pendant.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "ifia-necklace", name: "Ifia's Necklace", imgUrl: "./public/images/equips/pendant/ifia-necklace.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "juliet-pendant", name: "Juliet's Pendant", imgUrl: "./public/images/equips/pendant/juliet-pendant.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "machinator-pendant", name: "Machinator Pendant", imgUrl: "./public/images/equips/pendant/machinator-pendant.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "mystic-pendant", name: "Mystic Pendant", imgUrl: "./public/images/equips/pendant/mystic-pendant.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "pink-pendant", name: "Pink Pendant", imgUrl: "./public/images/equips/pendant/pink-pendant.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "purple-pendant", name: "Purple Pendant", imgUrl: "./public/images/equips/pendant/purple-pendant.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "rising-sun-pendant", name: "Rising Sun Pendant", imgUrl: "./public/images/equips/pendant/rising-sun-pendant.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "romeo-pendant", name: "Romeo's Pendant", imgUrl: "./public/images/equips/pendant/romeo-pendant.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "shackles-of-love", name: "Shackles of Love", imgUrl: "./public/images/equips/pendant/shackles-of-love.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "pendant", id: "veteran-crusader-pendant", name: "Veteran Crusader Pendant", imgUrl: "./public/images/equips/pendant/veteran-crusader-pendant.png", usedInSections: ["todd-sequence"] },
	
	{ itemType: "equip", category: "pocket", id: "gold-richie-handkerchief", name: "Gold Richie's Handkerchief", imgUrl: "./public/images/equips/pocket/gold-richie-handkerchief.png" },
	{ itemType: "equip", category: "pocket", id: "hilla-stone", name: "Stone of Eternal Life", imgUrl: "./public/images/equips/pocket/hilla-stone.png" },
	{ itemType: "equip", category: "pocket", id: "inverse-codex", name: "Inverse Codex", imgUrl: "./public/images/equips/pocket/inverse-codex.png" },
	{ itemType: "equip", category: "pocket", id: "phg", name: "Pink Holy Grail", imgUrl: "./public/images/equips/pocket/phg.png" },
	{ itemType: "equip", category: "pocket", id: "will-blue-book", name: "Cursed Blue Magic Book", imgUrl: "./public/images/equips/pocket/will-blue-book.png" },
	{ itemType: "equip", category: "pocket", id: "will-green-book", name: "Cursed Green Magic Book", imgUrl: "./public/images/equips/pocket/will-green-book.png" },
	{ itemType: "equip", category: "pocket", id: "will-red-book", name: "Cursed Enemy's Magic Book", imgUrl: "./public/images/equips/pocket/will-red-book.png", usedInSections: ["flames"] },
	{ itemType: "equip", category: "pocket", id: "will-yellow-book", name: "Cursed Yellow Magic Book", imgUrl: "./public/images/equips/pocket/will-yellow-book.png" },

	{ itemType: "equip", category: "ring", id: "breath-of-divinity", name: "Breath of Divinity", imgUrl: "./public/images/equips/ring/breath-of-divinity.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "ring", id: "elegant-ifia-ring", name: "Elegant Ifia's Ring", imgUrl: "./public/images/equips/ring/elegant-ifia-ring.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "ring", id: "fighter-ring", name: "Fighter's Ring", imgUrl: "./public/images/equips/ring/fighter-ring.png", usedInSections: ["set-effects"] },
	{ itemType: "equip", category: "ring", id: "giant-fear", name: "Giant Fear", imgUrl: "./public/images/equips/ring/giant-fear.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "ring", id: "hekaton-signet", name: "Hekaton Signet", imgUrl: "./public/images/equips/ring/hekaton-signet.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "ring", id: "hilla-fury", name: "Hilla's Fury", imgUrl: "./public/images/equips/ring/hilla-fury.png" },
	{ itemType: "equip", category: "ring", id: "ifia-ring", name: "Ifia's Ring", imgUrl: "./public/images/equips/ring/ifia-ring.png" },
	{ itemType: "equip", category: "ring", id: "kanna-ring", name: "Kanna's Treasure", imgUrl: "./public/images/equips/ring/kanna-ring.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "ring", id: "magnus-fury", name: "Magnus' Fury", imgUrl: "./public/images/equips/ring/magnus-fury.png" },
	{ itemType: "equip", category: "ring", id: "meister-signet", name: "Meister Signet", imgUrl: "./public/images/equips/ring/meister-signet.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "ring", id: "sbr", name: "Silver Blossom Ring", imgUrl: "./public/images/equips/ring/sbr.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "ring", id: "scarlet-ring", name: "Scarlet Ring", imgUrl: "./public/images/equips/ring/scarlet-ring.png", usedInSections: ["set-effects"] },

	{ itemType: "equip", category: "secondary", id: "deimos-darkness-shield", name: "Deimos Darkness Shield", imgUrl: "./public/images/equips/secondary/deimos-darkness-shield.png" },
	{ itemType: "equip", category: "secondary", id: "deimos-sage-shield", name: "Deimos Sage Shield", imgUrl: "./public/images/equips/secondary/deimos-sage-shield.png" },
	{ itemType: "equip", category: "secondary", id: "deimos-warrior-shield", name: "Deimos Warrior Shield", imgUrl: "./public/images/equips/secondary/deimos-warrior-shield.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-accursed-marble", name: "Princess Nou's Accursed Marble (Battle Mage)", imgUrl: "./public/images/equips/secondary/pnou-accursed-marble.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-arrow", name: "Princess Nou's Black Magic Arrow (Mercedes)", imgUrl: "./public/images/equips/secondary/pnou-arrow.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-arrowhead", name: "Princess Nou's Arrowhead (Wild Hunter)", imgUrl: "./public/images/equips/secondary/pnou-arrowhead.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-bracelet", name: "Princess Nou's Bracelet (Adele)", imgUrl: "./public/images/equips/secondary/pnou-bracelet.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-carte", name: "Princess Nou's Carte (Phantom)", imgUrl: "./public/images/equips/secondary/pnou-carte.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-charm", name: "Princess Nou's Charm (Night Lord)", imgUrl: "./public/images/equips/secondary/pnou-charm.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-controller", name: "Princess Nou's Controller (Xenon)", imgUrl: "./public/images/equips/secondary/pnou-controller.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-damp-book", name: "Princess Nou's Damp Book (Ice/Lightning Mage)", imgUrl: "./public/images/equips/secondary/pnou-damp-book.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-demon-aegis", name: "Princess Nou's Demon Aegis (Demon)", imgUrl: "./public/images/equips/secondary/pnou-demon-aegis.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-dragon-essence", name: "Princess Nou's Dragon Essence (Kaiser)", imgUrl: "./public/images/equips/secondary/pnou-dragon-essence.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-dragon-legacy", name: "Princess Nou's Dragon Legacy (Evan)", imgUrl: "./public/images/equips/secondary/pnou-dragon-legacy.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-falcon-eye", name: "Princess Nou's Falcon Eye (Captain)", imgUrl: "./public/images/equips/secondary/pnou-falcon-eye.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-feather", name: "Princess Nou's Feather (Bowmaster)", imgUrl: "./public/images/equips/secondary/pnou-feather.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-fire-bomb", name: "Princess Nou's Fire Bomb (Cannon Shooter)", imgUrl: "./public/images/equips/secondary/pnou-fire-bomb.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-flaming-book", name: "Princess Nou's Flaming Book (Fire/Poison Mage)", imgUrl: "./public/images/equips/secondary/pnou-flaming-book.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-floral-jewel", name: "Princess Nou's Floral Jewel (Cygnus Knights)", imgUrl: "./public/images/equips/secondary/pnou-floral-jewel.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-flower-chain", name: "Princess Nou's Flower Chain (Dark Knight)", imgUrl: "./public/images/equips/secondary/pnou-flower-chain.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-fox-marble", name: "Princess Nou's Fox Marble (Eunwol)", imgUrl: "./public/images/equips/secondary/pnou-fox-marble.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-golden-book", name: "Princess Nou's Golden Book (Bishop)", imgUrl: "./public/images/equips/secondary/pnou-golden-book.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-katara", name: "Princess Nou's Poisoned Sword (Dual Blade)", imgUrl: "./public/images/equips/secondary/pnou-katara.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-kinesis", name: "Princess Nou's Oriental King Chess Piece (Kinesis)", imgUrl: "./public/images/equips/secondary/pnou-kinesis.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-lucent-wings", name: "Princess Nou's Lucent Wings (Illium)", imgUrl: "./public/images/equips/secondary/pnou-lucent-wings.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-magical-whisper", name: "Princess Nou's Magical Whisper (Beast Tamer)", imgUrl: "./public/images/equips/secondary/pnou-magical-whisper.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-magnum", name: "Princess Nou's Magnum (Mechanic)", imgUrl: "./public/images/equips/secondary/pnou-magnum.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-medal", name: "Princess Nou's Medal (Hero)", imgUrl: "./public/images/equips/secondary/pnou-medal.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-megaton-charges", name: "Princess Nou's Megaton Charges (Blaster)", imgUrl: "./public/images/equips/secondary/pnou-megaton-charges.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-path", name: "Princess Nou's Path (Ark)", imgUrl: "./public/images/equips/secondary/pnou-path.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-pendulum", name: "Princess Nou's Pendulum (Aran)", imgUrl: "./public/images/equips/secondary/pnou-pendulum.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-purple-shadow", name: "Princess Nou's Purple Shadow (Shadower)", imgUrl: "./public/images/equips/secondary/pnou-purple-shadow.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-relic", name: "Princess Nou's Relic (Pathfinder)", imgUrl: "./public/images/equips/secondary/pnou-relic.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-rosario", name: "Princess Nou's Rosario (Paladin)", imgUrl: "./public/images/equips/secondary/pnou-rosario.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-skull-armor", name: "Princess Nou's Skull Armor (Viper)", imgUrl: "./public/images/equips/secondary/pnou-skull-armor.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-soul-orb", name: "Princess Nou's Soul Orb (Luminous)", imgUrl: "./public/images/equips/secondary/pnou-soul-orb.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-soul-ring", name: "Princess Nou's Soul Ring (Angelic Buster)", imgUrl: "./public/images/equips/secondary/pnou-soul-ring.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-soul-shield", name: "Princess Nou's Soul Shield (Mihile)", imgUrl: "./public/images/equips/secondary/pnou-soul-shield.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-tassel", name: "Princess Nou's Buchae Tassel (Ho Young)", imgUrl: "./public/images/equips/secondary/pnou-tassel.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-transmitter", name: "Princess Nou's Transmitter (Cadena)", imgUrl: "./public/images/equips/secondary/pnou-transmitter.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-wakizashi", name: "Princess Nou's Wakizashi (Hayato)", imgUrl: "./public/images/equips/secondary/pnou-wakizashi.png" },
	{ itemType: "equip", category: "secondary", id: "pnou-wreath", name: "Princess Nou's Wreath (Crossbow Master)", imgUrl: "./public/images/equips/secondary/pnou-wreath.png" },
	{ itemType: "equip", category: "secondary", id: "ruin-force-shield", name: "Ruin Force Shield", imgUrl: "./public/images/equips/secondary/ruin-force-shield.png" },

	{ itemType: "equip", category: "shoes", id: "abs-shoes", name: "Absolabs Shoes", imgUrl: "./public/images/equips/shoes/abs-shoes.png" },
	{ itemType: "equip", category: "shoes", id: "acs-shoes", name: "Arcaneshade Shoes", imgUrl: "./public/images/equips/shoes/acs-shoes.png", usedInSections: ["star-force"] },
	{ itemType: "equip", category: "shoes", id: "elite-heliseum-shoes", name: "Elite Heliseum Boots", imgUrl: "./public/images/equips/shoes/elite-heliseum-shoes.png", usedInSections: ["star-force"] },
	{ itemType: "equip", category: "shoes", id: "nova-shoes", name: "Nova Boots", imgUrl: "./public/images/equips/shoes/nova-shoes.png", usedInSections: ["star-force"] },
	{ itemType: "equip", category: "shoes", id: "tyrant-shoes", name: "Tyrant Boots", imgUrl: "./public/images/equips/shoes/tyrant-shoes.png", usedInSections: ["star-force"] },

	{ itemType: "equip", category: "shoulder", id: "abs-shoulder", name: "Absolabs Pauldron", imgUrl: "./public/images/equips/shoulder/abs-shoulder.png" },
	{ itemType: "equip", category: "shoulder", id: "acs-shoulder", name: "Arcaneshade Shoulder", imgUrl: "./public/images/equips/shoulder/acs-shoulder.png" },
	{ itemType: "equip", category: "shoulder", id: "black-bean-shoulder", name: "Black Bean Shoulderpads", imgUrl: "./public/images/equips/shoulder/black-bean-shoulder.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "shoulder", id: "hayato-shoulder", name: "Hayato's Treasure", imgUrl: "./public/images/equips/shoulder/hayato-shoulder.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "shoulder", id: "hekaton-shoulder", name: "Hekaton Pauldrons", imgUrl: "./public/images/equips/shoulder/hekaton-shoulder.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "shoulder", id: "inverse-shoulder", name: "Inverse Metal Shoulders", imgUrl: "./public/images/equips/shoulder/inverse-shoulder.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "shoulder", id: "magnus-shoulder", name: "Royal Black Metal Shoulder", imgUrl: "./public/images/equips/shoulder/magnus-shoulder.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "shoulder", id: "maple-treasure-shoulder", name: "Maple Treasure Epaulettes", imgUrl: "./public/images/equips/shoulder/maple-treasure-shoulder.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "shoulder", id: "masteria-shoulder", name: "Masteria Shoulderpads", imgUrl: "./public/images/equips/shoulder/masteria-shoulder.png", usedInSections: ["set-effects"] },
	{ itemType: "equip", category: "shoulder", id: "meister-spaulders", name: "Meister Spaulders", imgUrl: "./public/images/equips/shoulder/meister-spaulders.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "shoulder", id: "scarlet-shoulder", name: "Scarlet Shoulderpads", imgUrl: "./public/images/equips/shoulder/scarlet-pad.png", usedInSections: ["flames", "set-effects"] },
	{ itemType: "equip", category: "shoulder", id: "season-2-shoulder", name: "Season 2 Epaulet", imgUrl: "./public/images/equips/shoulder/season-2-shoulder.png", usedInSections: ["todd-sequence"] },

	{ itemType: "equip", category: "top", id: "faf-archer-top", name: "Eagle Eye Ranger Hood", imgUrl: "./public/images/equips/top/faf-archer-top.png" },
	{ itemType: "equip", category: "top", id: "faf-mage-top", name: "Eagle Eye Dunwitch Robe", imgUrl: "./public/images/equips/top/faf-mage-top.png" },
	{ itemType: "equip", category: "top", id: "faf-pirate-top", name: "Eagle Eye Wanderer Coat", imgUrl: "./public/images/equips/top/faf-pirate-top.png" },
	{ itemType: "equip", category: "top", id: "faf-thief-top", name: "Eagle Eye Assassin Shirt", imgUrl: "./public/images/equips/top/faf-thief-top.png" },
	{ itemType: "equip", category: "top", id: "faf-warrior-top", name: "Eagle Eye Warrior Armor", imgUrl: "./public/images/equips/top/faf-warrior-top.png", usedInSections: ["todd-sequence"] },

	{ itemType: "equip", category: "weapon", id: "abs-1h-axe", name: "Absolabs Rampage", imgUrl: "./public/images/equips/weapon/abs-1h-axe.png" },
	{ itemType: "equip", category: "weapon", id: "abs-1h-hammer", name: "Absolabs Gavel", imgUrl: "./public/images/equips/weapon/abs-1h-hammer.png" },
	{ itemType: "equip", category: "weapon", id: "abs-1h-sword", name: "Absolabs Durandal", imgUrl: "./public/images/equips/weapon/abs-1h-sword.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "weapon", id: "abs-2h-axe", name: "Absolabs Onslaught", imgUrl: "./public/images/equips/weapon/abs-2h-axe.png" },
	{ itemType: "equip", category: "weapon", id: "abs-2h-hammer", name: "Absolabs Truncheon", imgUrl: "./public/images/equips/weapon/abs-2h-hammer.png" },
	{ itemType: "equip", category: "weapon", id: "abs-2h-sword", name: "Absolabs Balmung", imgUrl: "./public/images/equips/weapon/abs-2h-sword.png" },
	{ itemType: "equip", category: "weapon", id: "abs-abow", name: "Absolabs Ancient Bow", imgUrl: "./public/images/equips/weapon/abs-abow.png" },
	{ itemType: "equip", category: "weapon", id: "abs-bow", name: "Absolabs Ichaival", imgUrl: "./public/images/equips/weapon/abs-bow.png" },
	{ itemType: "equip", category: "weapon", id: "abs-buchae", name: "Absolabs Monster Buchae", imgUrl: "./public/images/equips/weapon/abs-buchae.png" },
	{ itemType: "equip", category: "weapon", id: "abs-cane", name: "Absolabs Sceptre", imgUrl: "./public/images/equips/weapon/abs-cane.png" },
	{ itemType: "equip", category: "weapon", id: "abs-claw", name: "Absolabs Tarantula", imgUrl: "./public/images/equips/weapon/abs-claw.png" },
	{ itemType: "equip", category: "weapon", id: "abs-dagger", name: "Absolabs Shredder", imgUrl: "./public/images/equips/weapon/abs-dagger.png" },
	{ itemType: "equip", category: "weapon", id: "abs-dbg", name: "Absolabs Twin Astras", imgUrl: "./public/images/equips/weapon/abs-dbg.png" },
	{ itemType: "equip", category: "weapon", id: "abs-desperado", name: "Absolabs Blood Seeker", imgUrl: "./public/images/equips/weapon/abs-desperado.png" },
	{ itemType: "equip", category: "weapon", id: "abs-elaha", name: "Absolabs Kusanagi", imgUrl: "./public/images/equips/weapon/abs-elaha.png" },
	{ itemType: "equip", category: "weapon", id: "abs-energy-chain", name: "Absolabs Energy Chain", imgUrl: "./public/images/equips/weapon/abs-energy-chain.png" },
	{ itemType: "equip", category: "weapon", id: "abs-energy-sword", name: "Absolabs Electro Saber", imgUrl: "./public/images/equips/weapon/abs-energy-sword.png" },
	{ itemType: "equip", category: "weapon", id: "abs-fan", name: "Absolabs Incarnadine", imgUrl: "./public/images/equips/weapon/abs-fan.png" },
	{ itemType: "equip", category: "weapon", id: "abs-katana", name: "Absolabs Kogarasumaru", imgUrl: "./public/images/equips/weapon/abs-katana.png" },
	{ itemType: "equip", category: "weapon", id: "abs-katara", name: "Absolabs Katara", imgUrl: "./public/images/equips/weapon/abs-katara.png" },
	{ itemType: "equip", category: "weapon", id: "abs-knuckle", name: "Absolabs Ashen Fist", imgUrl: "./public/images/equips/weapon/abs-knuckle.png" },
	{ itemType: "equip", category: "weapon", id: "abs-lapis", name: "Lapis Type 8", imgUrl: "./public/images/equips/weapon/abs-lapis.png", usedInSections: ["flames"] },
	{ itemType: "equip", category: "weapon", id: "abs-magic-gauntlet", name: "Absolabs Magic Gauntlet", imgUrl: "./public/images/equips/weapon/abs-magic-gauntlet.png" },
	{ itemType: "equip", category: "weapon", id: "abs-pistol", name: "Absolabs Elite Magnum", imgUrl: "./public/images/equips/weapon/abs-pistol.png" },
	{ itemType: "equip", category: "weapon", id: "abs-polearm", name: "Absolabs Lochaber", imgUrl: "./public/images/equips/weapon/abs-polearm.png" },
	{ itemType: "equip", category: "weapon", id: "abs-psy-limiter", name: "Absolabs Psy-Limiter", imgUrl: "./public/images/equips/weapon/abs-psy-limiter.png" },
	{ itemType: "equip", category: "weapon", id: "abs-shining-rod", name: "Absolabs Aether Rod", imgUrl: "./public/images/equips/weapon/abs-shining-rod.png" },
	{ itemType: "equip", category: "weapon", id: "abs-siege-gun", name: "Absolabs Blast Cannon", imgUrl: "./public/images/equips/weapon/abs-siege-gun.png" },
	{ itemType: "equip", category: "weapon", id: "abs-soul-shooter", name: "Absolabs Draconic Arm", imgUrl: "./public/images/equips/weapon/abs-soul-shooter.png" },
	{ itemType: "equip", category: "weapon", id: "abs-spear", name: "Absolabs Assagai", imgUrl: "./public/images/equips/weapon/abs-spear.png" },
	{ itemType: "equip", category: "weapon", id: "abs-staff", name: "Absolabs Sage Staff", imgUrl: "./public/images/equips/weapon/abs-staff.png" },
	{ itemType: "equip", category: "weapon", id: "abs-tuner", name: "Absolabs Tuner", imgUrl: "./public/images/equips/weapon/abs-tuner.png" },
	{ itemType: "equip", category: "weapon", id: "abs-wand", name: "Absolabs Force Wand", imgUrl: "./public/images/equips/weapon/abs-wand.png" },
	{ itemType: "equip", category: "weapon", id: "abs-xbow", name: "Absolabs Astra Wing", imgUrl: "./public/images/equips/weapon/abs-xbow.png" },

	{ itemType: "equip", category: "weapon", id: "acs-1h-axe", name: "Arcaneshade Axe", imgUrl: "./public/images/equips/weapon/acs-1h-axe.png" },
	{ itemType: "equip", category: "weapon", id: "acs-1h-hammer", name: "Arcaneshade Hammer", imgUrl: "./public/images/equips/weapon/acs-1h-hammer.png" },
	{ itemType: "equip", category: "weapon", id: "acs-1h-sword", name: "Arcaneshade Saber", imgUrl: "./public/images/equips/weapon/acs-1h-sword.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "weapon", id: "acs-2h-axe", name: "Arcaneshade Two-handed Axe", imgUrl: "./public/images/equips/weapon/acs-2h-axe.png" },
	{ itemType: "equip", category: "weapon", id: "acs-2h-hammer", name: "Arcaneshade Two-handed Hammer", imgUrl: "./public/images/equips/weapon/acs-2h-hammer.png" },
	{ itemType: "equip", category: "weapon", id: "acs-2h-sword", name: "Arcaneshade Two-handed Sword", imgUrl: "./public/images/equips/weapon/acs-2h-sword.png" },
	{ itemType: "equip", category: "weapon", id: "acs-abow", name: "Arcaneshade Ancient Bow", imgUrl: "./public/images/equips/weapon/acs-abow.png" },
	{ itemType: "equip", category: "weapon", id: "acs-bow", name: "Arcaneshade Bow", imgUrl: "./public/images/equips/weapon/acs-bow.png" },
	{ itemType: "equip", category: "weapon", id: "acs-buchae", name: "Arcaneshade Transcendence Buchae", imgUrl: "./public/images/equips/weapon/acs-buchae.png" },
	{ itemType: "equip", category: "weapon", id: "acs-cane", name: "Arcaneshade Cane", imgUrl: "./public/images/equips/weapon/acs-cane.png" },
	{ itemType: "equip", category: "weapon", id: "acs-claw", name: "Arcaneshade Guards", imgUrl: "./public/images/equips/weapon/acs-claw.png" },
	{ itemType: "equip", category: "weapon", id: "acs-dagger", name: "Arcaneshade Dagger", imgUrl: "./public/images/equips/weapon/acs-dagger.png" },
	{ itemType: "equip", category: "weapon", id: "acs-dbg", name: "Arcaneshade Dual Bowgun", imgUrl: "./public/images/equips/weapon/acs-dbg.png" },
	{ itemType: "equip", category: "weapon", id: "acs-desperado", name: "Arcaneshade Desperado", imgUrl: "./public/images/equips/weapon/acs-desperado.png" },
	{ itemType: "equip", category: "weapon", id: "acs-elaha", name: "Arcaneshade Elaha", imgUrl: "./public/images/equips/weapon/acs-elaha.png" },
	{ itemType: "equip", category: "weapon", id: "acs-energy-chain", name: "Arcaneshade Energy Chain", imgUrl: "./public/images/equips/weapon/acs-energy-chain.png" },
	{ itemType: "equip", category: "weapon", id: "acs-energy-sword", name: "Arcaneshade Energy Sword", imgUrl: "./public/images/equips/weapon/acs-energy-sword.png" },
	{ itemType: "equip", category: "weapon", id: "acs-fan", name: "Arcaneshade Fan", imgUrl: "./public/images/equips/weapon/acs-fan.png" },
	{ itemType: "equip", category: "weapon", id: "acs-katana", name: "Arcaneshade Katana", imgUrl: "./public/images/equips/weapon/acs-katana.png" },
	{ itemType: "equip", category: "weapon", id: "acs-katara", name: "Arcaneshade Blade", imgUrl: "./public/images/equips/weapon/acs-katara.png" },
	{ itemType: "equip", category: "weapon", id: "acs-knuckle", name: "Arcaneshade Baghnakhs", imgUrl: "./public/images/equips/weapon/acs-knuckle.png" },
	{ itemType: "equip", category: "weapon", id: "acs-lapis", name: "Lapis Type 9", imgUrl: "./public/images/equips/weapon/acs-lapis.png" },
	{ itemType: "equip", category: "weapon", id: "acs-magic-gauntlet", name: "Arcaneshade Magic Gauntlet", imgUrl: "./public/images/equips/weapon/acs-magic-gauntlet.png" },
	{ itemType: "equip", category: "weapon", id: "acs-pistol", name: "Arcaneshade Pistol", imgUrl: "./public/images/equips/weapon/acs-pistol.png" },
	{ itemType: "equip", category: "weapon", id: "acs-polearm", name: "Arcaneshade Pole Arm", imgUrl: "./public/images/equips/weapon/acs-polearm.png" },
	{ itemType: "equip", category: "weapon", id: "acs-psy-limiter", name: "Arcaneshade Psy-Limiter", imgUrl: "./public/images/equips/weapon/acs-psy-limiter.png" },
	{ itemType: "equip", category: "weapon", id: "acs-shining-rod", name: "Arcaneshade Shining Rod", imgUrl: "./public/images/equips/weapon/acs-shining-rod.png" },
	{ itemType: "equip", category: "weapon", id: "acs-siege-gun", name: "Arcaneshade Siege Gun", imgUrl: "./public/images/equips/weapon/acs-siege-gun.png" },
	{ itemType: "equip", category: "weapon", id: "acs-soul-shooter", name: "Arcaneshade Soul Shooter", imgUrl: "./public/images/equips/weapon/acs-soul-shooter.png" },
	{ itemType: "equip", category: "weapon", id: "acs-spear", name: "Arcaneshade Spear", imgUrl: "./public/images/equips/weapon/acs-spear.png" },
	{ itemType: "equip", category: "weapon", id: "acs-staff", name: "Arcaneshade Staff", imgUrl: "./public/images/equips/weapon/acs-staff.png" },
	{ itemType: "equip", category: "weapon", id: "acs-tuner", name: "Arcaneshade Tuner", imgUrl: "./public/images/equips/weapon/acs-tuner.png" },
	{ itemType: "equip", category: "weapon", id: "acs-wand", name: "Arcaneshade Wand", imgUrl: "./public/images/equips/weapon/acs-wand.png" },
	{ itemType: "equip", category: "weapon", id: "acs-xbow", name: "Arcaneshade Crossbow", imgUrl: "./public/images/equips/weapon/acs-xbow.png" },

	{ itemType: "equip", category: "weapon", id: "faf-1h-axe", name: "Fafnir Twin Cleaver", imgUrl: "./public/images/equips/weapon/faf-1h-axe.png" },
	{ itemType: "equip", category: "weapon", id: "faf-1h-hammer", name: "Fafnir Golden Hammer", imgUrl: "./public/images/equips/weapon/faf-1h-hammer.png" },
	{ itemType: "equip", category: "weapon", id: "faf-1h-sword", name: "Fafnir Mystletainn", imgUrl: "./public/images/equips/weapon/faf-1h-sword.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "weapon", id: "faf-2h-axe", name: "Fafnir Battle Cleaver", imgUrl: "./public/images/equips/weapon/faf-2h-axe.png" },
	{ itemType: "equip", category: "weapon", id: "faf-2h-hammer", name: "Fafnir Lightninger", imgUrl: "./public/images/equips/weapon/faf-2h-hammer.png" },
	{ itemType: "equip", category: "weapon", id: "faf-2h-sword", name: "Fafnir Penitencia", imgUrl: "./public/images/equips/weapon/faf-2h-sword.png" },
	{ itemType: "equip", category: "weapon", id: "faf-abow", name: "Fafnir Ancient Bow", imgUrl: "./public/images/equips/weapon/faf-abow.png" },
	{ itemType: "equip", category: "weapon", id: "faf-bow", name: "Fafnir Bow", imgUrl: "./public/images/equips/weapon/faf-bow.png" },
	{ itemType: "equip", category: "weapon", id: "faf-buchae", name: "Fafnir Dragon Buchae", imgUrl: "./public/images/equips/weapon/faf-buchae.png" },
	{ itemType: "equip", category: "weapon", id: "faf-cane", name: "Fafnir Clair Ciel", imgUrl: "./public/images/equips/weapon/faf-cane.png" },
	{ itemType: "equip", category: "weapon", id: "faf-claw", name: "Fafnir Risk Holder", imgUrl: "./public/images/equips/weapon/faf-claw.png" },
	{ itemType: "equip", category: "weapon", id: "faf-dagger", name: "Fafnir Damascus", imgUrl: "./public/images/equips/weapon/faf-dagger.png" },
	{ itemType: "equip", category: "weapon", id: "faf-dbg", name: "Fafnir Dual Bowguns", imgUrl: "./public/images/equips/weapon/faf-dbg.png" },
	{ itemType: "equip", category: "weapon", id: "faf-desperado", name: "Fafnir Death Bringer", imgUrl: "./public/images/equips/weapon/faf-desperado.png" },
	{ itemType: "equip", category: "weapon", id: "faf-elaha", name: "Fafnir Gigastein", imgUrl: "./public/images/equips/weapon/faf-elaha.png" },
	{ itemType: "equip", category: "weapon", id: "faf-energy-chain", name: "Fafnir Energy Chain", imgUrl: "./public/images/equips/weapon/faf-energy-chain.png" },
	{ itemType: "equip", category: "weapon", id: "faf-energy-sword", name: "Fafnir Split Edge", imgUrl: "./public/images/equips/weapon/faf-energy-sword.png" },
	{ itemType: "equip", category: "weapon", id: "faf-fan", name: "Fafnir Indigo Flash", imgUrl: "./public/images/equips/weapon/faf-fan.png", usedInSections: ["flames"] },
	{ itemType: "equip", category: "weapon", id: "faf-katana", name: "Fafnir Raven Ring", imgUrl: "./public/images/equips/weapon/faf-katana.png" },
	{ itemType: "equip", category: "weapon", id: "faf-katara", name: "Fafnir Rapid Edge", imgUrl: "./public/images/equips/weapon/faf-katara.png" },
	{ itemType: "equip", category: "weapon", id: "faf-knuckle", name: "Fafnir Fenrir Talon", imgUrl: "./public/images/equips/weapon/faf-knuckle.png" },
	{ itemType: "equip", category: "weapon", id: "faf-lapis", name: "Lapis Type 7", imgUrl: "./public/images/equips/weapon/faf-lapis.png" },
	{ itemType: "equip", category: "weapon", id: "faf-magic-gauntlet", name: "Fafnir Magic Gauntlet", imgUrl: "./public/images/equips/weapon/faf-magic-gauntlet.png" },
	{ itemType: "equip", category: "weapon", id: "faf-pistol", name: "Fafnir Zeliska", imgUrl: "./public/images/equips/weapon/faf-pistol.png" },
	{ itemType: "equip", category: "weapon", id: "faf-polearm", name: "Fafnir Moon Glaive", imgUrl: "./public/images/equips/weapon/faf-polearm.png" },
	{ itemType: "equip", category: "weapon", id: "faf-psy-limiter", name: "Fafnir Psy-Limiter", imgUrl: "./public/images/equips/weapon/faf-psy-limiter.png" },
	{ itemType: "equip", category: "weapon", id: "faf-shining-rod", name: "Fafnir Mana Cradle", imgUrl: "./public/images/equips/weapon/faf-shining-rod.png" },
	{ itemType: "equip", category: "weapon", id: "faf-siege-gun", name: "Fafnir Luster Cannon", imgUrl: "./public/images/equips/weapon/faf-siege-gun.png" },
	{ itemType: "equip", category: "weapon", id: "faf-soul-shooter", name: "Fafnir Angelic Shooter", imgUrl: "./public/images/equips/weapon/faf-soul-shooter.png" },
	{ itemType: "equip", category: "weapon", id: "faf-spear", name: "Fafnir Bionarc", imgUrl: "./public/images/equips/weapon/faf-spear.png" },
	{ itemType: "equip", category: "weapon", id: "faf-staff", name: "Fafnir Mana Crown", imgUrl: "./public/images/equips/weapon/faf-staff.png" },
	{ itemType: "equip", category: "weapon", id: "faf-tuner", name: "Fafnir Forgiveness", imgUrl: "./public/images/equips/weapon/faf-tuner.png" },
	{ itemType: "equip", category: "weapon", id: "faf-wand", name: "Fafnir Mana Taker", imgUrl: "./public/images/equips/weapon/faf-wand.png" },
	{ itemType: "equip", category: "weapon", id: "faf-xbow", name: "Fafnir Crossbow", imgUrl: "./public/images/equips/weapon/faf-xbow.png" },

	{ itemType: "equip", category: "weapon", id: "genesis-1h-axe", name: "Genesis Axe", imgUrl: "./public/images/equips/weapon/genesis-1h-axe.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-1h-hammer", name: "Genesis Hammer", imgUrl: "./public/images/equips/weapon/genesis-1h-hammer.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-1h-sword", name: "Genesis Sabre", imgUrl: "./public/images/equips/weapon/genesis-1h-sword.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-2h-axe", name: "Genesis Two-handed Axe", imgUrl: "./public/images/equips/weapon/genesis-2h-axe.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-2h-hammer", name: "Genesis Two-handed Hammer", imgUrl: "./public/images/equips/weapon/genesis-2h-hammer.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-2h-sword", name: "Genesis Two-handed Sword", imgUrl: "./public/images/equips/weapon/genesis-2h-sword.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-abow", name: "Genesis Ancient Bow", imgUrl: "./public/images/equips/weapon/genesis-abow.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-bow", name: "Genesis Bow", imgUrl: "./public/images/equips/weapon/genesis-bow.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-buchae", name: "Genesis Buchae", imgUrl: "./public/images/equips/weapon/genesis-buchae.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-cane", name: "Genesis Cane", imgUrl: "./public/images/equips/weapon/genesis-cane.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-claw", name: "Genesis Guards", imgUrl: "./public/images/equips/weapon/genesis-claw.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-dagger", name: "Genesis Dagger", imgUrl: "./public/images/equips/weapon/genesis-dagger.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-dbg", name: "Genesis Dual Bowgun", imgUrl: "./public/images/equips/weapon/genesis-dbg.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-desperado", name: "Genesis Desperado", imgUrl: "./public/images/equips/weapon/genesis-desperado.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-elaha", name: "Genesis Elaha", imgUrl: "./public/images/equips/weapon/genesis-elaha.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-energy-chain", name: "Genesis Chain", imgUrl: "./public/images/equips/weapon/genesis-energy-chain.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-energy-sword", name: "Genesis Energy Sword", imgUrl: "./public/images/equips/weapon/genesis-energy-sword.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-fan", name: "Genesis Fan", imgUrl: "./public/images/equips/weapon/genesis-fan.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-katana", name: "Genesis Katana", imgUrl: "./public/images/equips/weapon/genesis-katana.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-katara", name: "Genesis Blade", imgUrl: "./public/images/equips/weapon/genesis-katara.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-knuckle", name: "Genesis Claw", imgUrl: "./public/images/equips/weapon/genesis-knuckle.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-lapis", name: "Lapis Type 10", imgUrl: "./public/images/equips/weapon/genesis-lapis.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-magic-gauntlet", name: "Genesis Magic Gauntlet", imgUrl: "./public/images/equips/weapon/genesis-magic-gauntlet.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-pistol", name: "Genesis Pistol", imgUrl: "./public/images/equips/weapon/genesis-pistol.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-polearm", name: "Genesis Pole Arm", imgUrl: "./public/images/equips/weapon/genesis-polearm.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-psy-limiter", name: "Genesis ESP Limiter", imgUrl: "./public/images/equips/weapon/genesis-psy-limiter.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-shining-rod", name: "Genesis Shining Rod", imgUrl: "./public/images/equips/weapon/genesis-shining-rod.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-siege-gun", name: "Genesis Siege Gun", imgUrl: "./public/images/equips/weapon/genesis-siege-gun.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-soul-shooter", name: "Genesis Soul Shooter", imgUrl: "./public/images/equips/weapon/genesis-soul-shooter.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-spear", name: "Genesis Spear", imgUrl: "./public/images/equips/weapon/genesis-spear.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-staff", name: "Genesis Staff", imgUrl: "./public/images/equips/weapon/genesis-staff.png", usedInSections: ["flames", "set-effects"] },
	{ itemType: "equip", category: "weapon", id: "genesis-tuner", name: "Genesis Tuner", imgUrl: "./public/images/equips/weapon/genesis-tuner.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-wand", name: "Genesis Wand", imgUrl: "./public/images/equips/weapon/genesis-wand.png" },
	{ itemType: "equip", category: "weapon", id: "genesis-xbow", name: "Genesis Crossbow", imgUrl: "./public/images/equips/weapon/genesis-xbow.png" },

	{ itemType: "equip", category: "weapon", id: "scarlet-1h-axe", name: "Scarlet War Cleaver", imgUrl: "./public/images/equips/weapon/scarlet-1h-axe.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-1h-hammer", name: "Scarlet War Hammer", imgUrl: "./public/images/equips/weapon/scarlet-1h-hammer.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-1h-sword", name: "Scarlet Gladius", imgUrl: "./public/images/equips/weapon/scarlet-1h-sword.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-2h-axe", name: "Scarlet Battle Axe", imgUrl: "./public/images/equips/weapon/scarlet-2h-axe.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-2h-hammer", name: "Scarlet Battle Hammer", imgUrl: "./public/images/equips/weapon/scarlet-2h-hammer.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-2h-sword", name: "Scarlet Claymore", imgUrl: "./public/images/equips/weapon/scarlet-2h-sword.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-bow", name: "Scarlet Battle Bow", imgUrl: "./public/images/equips/weapon/scarlet-bow.png", usedInSections: ["set-effects"] },
	{ itemType: "equip", category: "weapon", id: "scarlet-cane", name: "Scarlet Persona", imgUrl: "./public/images/equips/weapon/scarlet-cane.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-claw", name: "Scarlet Dark Slane", imgUrl: "./public/images/equips/weapon/scarlet-claw.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-dagger", name: "Scarlet Qatar", imgUrl: "./public/images/equips/weapon/scarlet-dagger.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-dbg", name: "Scarlet Eagle Wing", imgUrl: "./public/images/equips/weapon/scarlet-dbg.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-desperado", name: "Scarlet Death Bringer", imgUrl: "./public/images/equips/weapon/scarlet-desperado.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-energy-sword", name: "Scarlet Split Edge", imgUrl: "./public/images/equips/weapon/scarlet-energy-sword.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-fan", name: "Scarlet Fan", imgUrl: "./public/images/equips/weapon/scarlet-fan.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-katana", name: "Scarlet Katana", imgUrl: "./public/images/equips/weapon/scarlet-katana.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-katara", name: "Scarlet Blade", imgUrl: "./public/images/equips/weapon/scarlet-katara.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-knuckle", name: "Scarlet Gryphon Claw", imgUrl: "./public/images/equips/weapon/scarlet-knuckle.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-pistol", name: "Scarlet Infinity", imgUrl: "./public/images/equips/weapon/scarlet-pistol.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-polearm", name: "Scarlet Halberd", imgUrl: "./public/images/equips/weapon/scarlet-polearm.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-shining-rod", name: "Scarlet Thanatos", imgUrl: "./public/images/equips/weapon/scarlet-shining-rod.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-siege-gun", name: "Scarlet Crash", imgUrl: "./public/images/equips/weapon/scarlet-siege-gun.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-soul-shooter", name: "Scarlet Angelic Shooter", imgUrl: "./public/images/equips/weapon/scarlet-soul-shooter.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-spear", name: "Scarlet Spear", imgUrl: "./public/images/equips/weapon/scarlet-spear.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-staff", name: "Scarlet Battle Staff", imgUrl: "./public/images/equips/weapon/scarlet-staff.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-wand", name: "Scarlet Evil Wand", imgUrl: "./public/images/equips/weapon/scarlet-wand.png" },
	{ itemType: "equip", category: "weapon", id: "scarlet-xbow", name: "Scarlet Crossbow", imgUrl: "./public/images/equips/weapon/scarlet-xbow.png" },

	{ itemType: "equip", category: "weapon", id: "briser-1h-sword", name: "Briser Shortsword", imgUrl: "./public/images/equips/weapon/briser-1h-sword.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "weapon", id: "dragon-1h-sword", name: "Dragon Carabella", imgUrl: "./public/images/equips/weapon/dragon-1h-sword.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "weapon", id: "empress-1h-sword", name: "Lion Heart Cutlass", imgUrl: "./public/images/equips/weapon/empress-1h-sword.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "weapon", id: "jaihin-1h-sword", name: "Jaihin Shortsword", imgUrl: "./public/images/equips/weapon/jaihin-1h-sword.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "weapon", id: "necro-1h-sword", name: "Necro Terror", imgUrl: "./public/images/equips/weapon/necro-1h-sword.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "weapon", id: "rvl-1h-sword", name: "Royal Von Leon Saber", imgUrl: "./public/images/equips/weapon/rvl-1h-sword.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "weapon", id: "utgard-1h-sword", name: "Utgard Shortsword", imgUrl: "./public/images/equips/weapon/utgard-1h-sword.png", usedInSections: ["todd-sequence"] },
	{ itemType: "equip", category: "weapon", id: "zakum-1h-sword", name: "Zakum Poisonic Sword", imgUrl: "./public/images/equips/weapon/zakum-1h-sword.png", usedInSections: ["todd-sequence"] },
];

module.exports = equipTabIcons;