var commonSetItems = {
	hat: [
		{ setType: "none", id: "cvell-hat", image: "./public/images/equips/hat/chaos-bellum.png", name: "Chaos Bellum Hat", isLuckyItem: true, itemPriority: 0 },
	],
	gloves: [
		{ setType: "none", id: "hero-gloves", image: "./public/images/equips/gloves/hero-gloves.png", name: "Hero's Gloves", isLuckyItem: true, itemPriority: 20 },
		{ setType: "none", id: "mu-gong-gloves", image: "./public/images/equips/gloves/mu-gong-gloves.png", name: "Mu Gong's Gloves", isLuckyItem: true, itemPriority: 20 },
		{ setType: "none", id: "so-gong-gloves", image: "./public/images/equips/gloves/so-gong-gloves.png", name: "So Gong's Gloves", isLuckyItem: true, itemPriority: 20 },
		{ setType: "none", id: "expert-gloves", image: "./public/images/equips/gloves/expert-gloves.png", name: "Expert's Gloves", isLuckyItem: true, itemPriority: 20 },
		{ setType: "none", id: "expert-apprentice-gloves", image: "./public/images/equips/gloves/expert-apprentice-gloves.png", name: "Expert Apprentice's Gloves", isLuckyItem: true, itemPriority: 20 },
	],
	face: [
		{ setType: "hardBossAcc", id: "lotus-mark", image: "./public/images/equips/face/lotus-mark.png", name: "Loose Control Machine Mark" },
		{ setType: "none", id: "frontier-b-chicle", image: "./public/images/equips/face/frontier-b-chicle.png", name: "Frontier B Black Chicle" },
		{ setType: "bossAcc", id: "condense-crystal", image: "./public/images/equips/face/condensed-crystal.png", name: "Condensed Strength Crystalline" },
	],
	eye: [
		{ setType: "hardBossAcc", id: "damien-eye", image: "./public/images/equips/eye/damien-eye.png", name: "Magical Eye Patch" },
		{ setType: "bossAcc", id: "papu-mark", image: "./public/images/equips/eye/papulatus-mark.png", name: "Papulatus Mark" },
		{ setType: "bossAcc", id: "bbm", image: "./public/images/equips/eye/black-bean-mark.png", name: "Black Bean Mark" },
		{ setType: "bossAcc", id: "aqua-eye", image: "./public/images/equips/eye/aqua-letter.png", name: "Aqua Letter Eye Decoration" },
	],
	badge: [
		{ setType: "hardBossAcc", id: "genesis-badge", image: "./public/images/equips/badge/genesis-badge.png", name: "Badge of Beginning" },
		{ setType: "bossAcc", id: "ventus-badge", image: "./public/images/equips/badge/ventus-badge.png", name: "Crystal Ventus Badge" },
		{ setType: "none", id: "lord-skull-badge", image: "./public/images/equips/badge/lord-skull-badge.png", name: "Lord Skull Badge" },
		{ setType: "none", id: "lania-badge", image: "./public/images/equips/badge/lania-box.png", name: "Lania's Triple Lunch Box" },
		{ setType: "none", id: "hospital-badge", image: "./public/images/equips/badge/hospital-director-badge.png", name: "Hospital Director's Badge" },
	],
	earring: [
		{ setType: "none", id: "ocean-glow-earring", image: "./public/images/equips/earring/ocean-glow-earring.png", name: "Ocean Glow Earrings" },
		{ setType: "inverse", id: "inverse-earrings", image: "./public/images/equips/earring/inverse-jewel-earring.png", name: "Inverse Jewel Earring" },
		{ setType: "meister", id: "meister-studs", image: "./public/images/equips/earring/meister-studs.png", name: "Meister Ear Studs" },
		{ setType: "none", id: "scarlet-earring", image: "./public/images/equips/earring/scarlet-earring.png", name: "Scarlet Earring", isLuckyItem: true, itemPriority: 10 },
		{ setType: "bossAcc", id: "dea-sidus", image: "./public/images/equips/earring/dea-sidus.png", name: "Dea Sidus Earrings" },
		{ setType: "bossAcc", id: "will-o-wisps", image: "./public/images/equips/earring/will-o-wisps.png", name: "Will o' the Wisps" },
	],
	pendant: [
		{ setType: "hardBossAcc", id: "hilla-pendant", image: "./public/images/equips/pendant/hilla-pendant.png", name: "Source of Pain" },
		{ setType: "none", id: "frontier-c-pendant", image: "./public/images/equips/pendant/frontier-c-pendant.png", name: "Frontier C White Pendant" },
		{ setType: "bossAcc", id: "dom-pendant", image: "./public/images/equips/pendant/dom-pendant.png", name: "Dominator Pendant" },
		{ setType: "none", id: "frontier-b-pendant", image: "./public/images/equips/pendant/frontier-b-pendant.png", name: "Frontier B Black Pendant" },
		{ setType: "none", id: "rising-sun-pendant", image: "./public/images/equips/pendant/rising-sun-pendant.png", name: "Rising Sun Pendant" },
		{ setType: "bossAcc", id: "mach-pendant", image: "./public/images/equips/pendant/machinator-pendant.png", name: "Machinator Pendant" },
		{ setType: "bossAcc", id: "cht-pendant", image: "./public/images/equips/pendant/cht-pendant.png", name: "Chaos Horntail Necklace" },
		{ setType: "bossAcc", id: "ht-pendant", image: "./public/images/equips/pendant/ht-pendant.png", name: "Horned Tail Necklace" },
	],
	ring: [
		{ setType: "none", id: "breath-of-divinity", image: "./public/images/equips/ring/breath-of-divinity.png", name: "Breath of Divinity" },
		{ setType: "meister", id: "meister-signet", image: "./public/images/equips/ring/meister-signet.png", name: "Meister Signet" },
		{ setType: "sengoku", id: "kanna-ring", image: "./public/images/equips/ring/kanna-ring.png", name: "Kanna's Treasure" },
		{ setType: "none", id: "hekaton-signet", image: "./public/images/equips/ring/hekaton-signet.png", name: "Hekaton Signet" },
		{ setType: "none", id: "scarlet-ring", image: "./public/images/equips/ring/scarlet-ring.png", name: "Scarlet Ring", isLuckyItem: true, itemPriority: 30 },
		{ setType: "bossAcc", id: "elegant-ifia-ring", image: "./public/images/equips/ring/elegant-ifia-ring.png", name: "Elegant Ifia Ring" },
		{ setType: "bossAcc", id: "sbr", image: "./public/images/equips/ring/sbr.png", name: "Silver Blossom Ring" },
		{ setType: "none", id: "magnus-fury", image: "./public/images/equips/ring/magnus-fury.png", name: "Magnus' Fury" },
		{ setType: "none", id: "hilla-fury", image: "./public/images/equips/ring/hilla-fury.png", name: "Hilla's Fury" },
		{ setType: "none", id: "fighter-ring", image: "./public/images/equips/ring/fighter-ring.png", name: "Fighter's Ring", isLuckyItem: true, itemPriority: 31 },
	],
	belt: [
		{ setType: "hardBossAcc", id: "fantasy-belt", image: "./public/images/equips/belt/fantasy-belt.png", name: "Fantasy Belt" },
		{ setType: "bossAcc", id: "angry-zakum-belt", image: "./public/images/equips/belt/angry-zakum-belt.png", name: "Angry Zakum's Belt" },
		{ setType: "sengoku", id: "ayame-belt", image: "./public/images/equips/belt/ayame-belt.png", name: "Ayame's Treasure" },
		{ setType: "bossAcc", id: "golden-clover-belt", image: "./public/images/equips/belt/golden-clover-belt.png", name: "Golden Clover Belt" },
	],
	pocket: [
		{ setType: "hardBossAcc", id: "will-red-book", image: "./public/images/equips/pocket/will-red-book.png", name: "Cursed Enemy Magic Book" },
		{ setType: "hardBossAcc", id: "will-blue-book", image: "./public/images/equips/pocket/will-blue-book.png", name: "Cursed Blue Magic Book" },
		{ setType: "hardBossAcc", id: "will-green-book", image: "./public/images/equips/pocket/will-green-book.png", name: "Cursed Green Magic Book" },
		{ setType: "hardBossAcc", id: "will-yellow-book", image: "./public/images/equips/pocket/will-yellow-book.png", name: "Cursed Yellow Magic Book" },
		{ setType: "inverse", id: "inverse-codex", image: "./public/images/equips/pocket/inverse-codex.png", name: "Inverse Codex" },
		{ setType: "bossAcc", id: "phg", image: "./public/images/equips/pocket/phg.png", name: "Pink Holy Grail" },
		{ setType: "bossAcc", id: "hilla-stone", image: "./public/images/equips/pocket/hilla-stone.png", name: "Stone of Eternal Life" },
		{ setType: "none", id: "gold-richie-handkerchief", image: "./public/images/equips/pocket/gold-richie-handkerchief.png", name: "Gold Richie's Handkerchief" },
	],
	shoulder: [
		{ setType: "inverse", id: "inverse-shoulder", image: "./public/images/equips/shoulder/inverse-shoulder.png", name: "Inverse Metal Shoulders" },
		{ setType: "meister", id: "meister-spaulders", image: "./public/images/equips/shoulder/meister-spaulders.png", name: "Meister Spaulders" },
		{ setType: "sengoku", id: "hayato-shoulder", image: "./public/images/equips/shoulder/hayato-shoulder.png", name: "Hayato's Treasure" },
		{ setType: "none", id: "scarlet-pad", image: "./public/images/equips/shoulder/scarlet-pad.png", name: "Scarlet Shoulderpads", isLuckyItem: true, itemPriority: 50 },
		{ setType: "none", id: "masteria-shoulder", image: "./public/images/equips/shoulder/masteria-shoulder.png", name: "Masteria Shoulderpads", isLuckyItem: true, itemPriority: 50 },
		{ setType: "bossAcc", id: "magnus-shoulder", image: "./public/images/equips/shoulder/magnus-shoulder.png", name: "Royal Black Metal Shoulder" },
	],
	heart: [
		{ setType: "none", id: "outlaw-heart", image: "./public/images/equips/heart/outlaw-heart.png", name: "Outlaw Heart" },
		{ setType: "hardBossAcc", id: "black-heart", image: "./public/images/equips/heart/black-heart.png", name: "Black Heart" },
		{ setType: "none", id: "liquid-metal-heart", image: "./public/images/equips/heart/liquid-metal-heart.png", name: "Liquid Metal Heart" },
		{ setType: "none", id: "beautyroid-heart", image: "./public/images/equips/heart/beautyroid-heart.png", name: "Sincere Beautyroid Heart" },
		{ setType: "none", id: "titanium-heart", image: "./public/images/equips/heart/titanium-heart.png", name: "Titanium Heart" },
	],
	android: [
		{ setType: "none", id: "broid", image: "./public/images/equips/android/broid.png", name: "Battle-roid" },
	],
	emblem: [
		{ setType: "none", id: "seed-legend", image: "./public/images/equips/emblem/seed-legend-emblem.png", name: "The Seed Legend Emblem" },
		{ setType: "none", id: "seed-master", image: "./public/images/equips/emblem/seed-master-emblem.png", name: "The Seed Master Emblem" },
		{ setType: "none", id: "seed-expert", image: "./public/images/equips/emblem/seed-expert-emblem.png", name: "The Seed Expert Emblem" },
	],
	medal: [
		{ setType: "none", id: "chef-medal", image: "./public/images/equips/medal/chef-medal.png", name: "Absolute Palate Legendary Chef Medal" },
		{ setType: "none", id: "monster-park-medal", image: "./public/images/equips/medal/monster-park-medal.png", name: "7-Day Monster Parker" },
	]
}

module.exports = commonSetItems;