var warriorSetItems = {
	hat: [
		{ setType: "acs", id: "acs-warrior-hat", image: "./public/images/equips/hat/acs-knight-hat.png", name: "Arcaneshade Knight Hat" },
		{ setType: "abs", id: "abs-warrior-hat", image: "./public/images/equips/hat/abs-bastion-helm.png", name: "Absolabs Bastion Helm" },
		{ setType: "faf", id: "faf-warrior-hat", image: "./public/images/equips/hat/faf-warrior-hat.png", name: "Highness Warrior Helm" },
	],
	face: [
		{ setType: "none", id: "meister-symbol", image: "./public/images/equips/face/meister-symbol.png", name: "Shiny Red Warrior Meister Symbol" },
	],
	top: [
		{ setType: "acs", id: "acs-knight-suit", image: "./public/images/equips/overall/acs-knight-suit.png", name: "Arcaneshade Knight Suit", isOverall: true },
		{ setType: "abs", id: "abs-warrior-overall", image: "./public/images/equips/overall/abs-warrior-overall.png", name: "Absolabs Bastion Hauberk", isOverall: true },
		{ setType: "faf", id: "faf-warrior-top", image: "./public/images/equips/top/faf-warrior-top.png", name: "Eagle Eye Warrior Armor" },
	],
	bottom: [
		{ setType: "faf", id: "faf-warrior-bottom", image: "./public/images/equips/bottom/faf-warrior-bottom.png", name: "Trickster Warrior Pants" },
	],
	shoes: [
		{ setType: "acs", id: "acs-warrior-shoes", image: "./public/images/equips/shoes/acs-shoes.png", name: "Arcaneshade Knight Shoes" },
		{ setType: "abs", id: "abs-warrior-shoes", image: "./public/images/equips/shoes/abs-shoes.png", name: "Absolabs Bastion Greaves" },
		{ setType: "none", id: "tyrant-shoes", image: "./public/images/equips/shoes/tyrant-shoes.png", name: "Tyrant Hyades Boots" },
	],
	gloves: [
		{ setType: "acs", id: "acs-warrior-glove", image: "./public/images/equips/gloves/acs-glove.png", name: "Arcaneshade Knight Mitts" },
		{ setType: "abs", id: "abs-warrior-glove", image: "./public/images/equips/gloves/abs-glove.png", name: "Absolabs Bastion Gauntlets" },
		{ setType: "none", id: "tyrant-gloves", image: "./public/images/equips/gloves/tyrant-gloves.png", name: "Tyrant Hyades Gloves" },
	],
	cape: [
		{ setType: "acs", id: "acs-warrior-cape", image: "./public/images/equips/cape/acs-cape.png", name: "Arcaneshade Knight Cape" },
		{ setType: "abs", id: "abs-warrior-cape", image: "./public/images/equips/cape/abs-cape.png", name: "Absolabs Bastion Cloak" },
		{ setType: "none", id: "tyrant-cape", image: "./public/images/equips/cape/tyrant-cape.png", name: "Tyrant Hyades Cloak" },
	],
	shoulder: [
		{ setType: "acs", id: "acs-warrior-shoulder", image: "./public/images/equips/shoulder/acs-shoulder.png", name: "Arcaneshade Knight Shoulder" },
		{ setType: "abs", id: "abs-warrior-shoulder", image: "./public/images/equips/shoulder/abs-shoulder.png", name: "Absolabs Bastion Pauldron" },
	],
	weapon: [
		{ setType: "none", id: "genesis-1h-sword", image: "./public/images/equips/weapon/genesis-1h-sword.png", name: "Genesis Sabre", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "genesis-2h-sword", image: "./public/images/equips/weapon/genesis-2h-sword.png", name: "Genesis Two-handed Sword", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "genesis-1h-axe", image: "./public/images/equips/weapon/genesis-1h-axe.png", name: "Genesis Axe", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "genesis-2h-axe", image: "./public/images/equips/weapon/genesis-2h-axe.png", name: "Genesis Two-handed Axe", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "genesis-1h-hammer", image: "./public/images/equips/weapon/genesis-1h-hammer.png", name: "Genesis Hammer", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "genesis-2h-hammer", image: "./public/images/equips/weapon/genesis-2h-hammer.png", name: "Genesis Two-handed Hammer", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "genesis-spear", image: "./public/images/equips/weapon/genesis-spear.png", name: "Genesis Spear", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "genesis-polearm", image: "./public/images/equips/weapon/genesis-polearm.png", name: "Genesis Pole Arm", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "genesis-desperado", image: "./public/images/equips/weapon/genesis-desperado.png", name: "Genesis Desperado", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "genesis-elaha", image: "./public/images/equips/weapon/genesis-elaha.png", name: "Genesis Elaha", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "genesis-lapis", image: "./public/images/equips/weapon/genesis-lapis.png", name: "Lapis Type 10", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "genesis-katana", image: "./public/images/equips/weapon/genesis-katana.png", name: "Genesis Katana", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "genesis-tuner", image: "./public/images/equips/weapon/genesis-tuner.png", name: "Genesis Tuner", isLuckyItem: true, itemPriority: 100 },

		{ setType: "acs", id: "acs-1h-sword", image: "./public/images/equips/weapon/acs-1h-sword.png", name: "Arcaneshade Saber" },
		{ setType: "acs", id: "acs-2h-sword", image: "./public/images/equips/weapon/acs-2h-sword.png", name: "Arcaneshade Two-handed Sword" },
		{ setType: "acs", id: "acs-1h-axe", image: "./public/images/equips/weapon/acs-1h-axe.png", name: "Arcaneshade Axe" },
		{ setType: "acs", id: "acs-2h-axe", image: "./public/images/equips/weapon/acs-2h-axe.png", name: "Arcaneshade Two-handed Axe" },
		{ setType: "acs", id: "acs-1h-hammer", image: "./public/images/equips/weapon/acs-1h-hammer.png", name: "Arcaneshade Hammer" },
		{ setType: "acs", id: "acs-2h-hammer", image: "./public/images/equips/weapon/acs-2h-hammer.png", name: "Arcaneshade Two-handed Hammer" },
		{ setType: "acs", id: "acs-spear", image: "./public/images/equips/weapon/acs-spear.png", name: "Arcaneshade Spear" },
		{ setType: "acs", id: "acs-polearm", image: "./public/images/equips/weapon/acs-polearm.png", name: "Arcaneshade Pole Arm" },
		{ setType: "acs", id: "acs-desperado", image: "./public/images/equips/weapon/acs-desperado.png", name: "Arcaneshade Desperado" },
		{ setType: "acs", id: "acs-elaha", image: "./public/images/equips/weapon/acs-elaha.png", name: "Arcaneshade Elaha" },
		{ setType: "acs", id: "acs-lapis", image: "./public/images/equips/weapon/acs-lapis.png", name: "Lapis Type 9" },
		{ setType: "acs", id: "acs-katana", image: "./public/images/equips/weapon/acs-katana.png", name: "Arcaneshade Katana" },
		{ setType: "abs", id: "acs-tuner", image: "./public/images/equips/weapon/acs-tuner.png", name: "Arcaneshade Tuner" },

		{ setType: "abs", id: "abs-1h-sword", image: "./public/images/equips/weapon/abs-1h-sword.png", name: "Absolabs Durandal" },
		{ setType: "abs", id: "abs-2h-sword", image: "./public/images/equips/weapon/abs-2h-sword.png", name: "Absolabs Balmung" },
		{ setType: "abs", id: "abs-1h-axe", image: "./public/images/equips/weapon/abs-1h-axe.png", name: "Absolabs Rampage" },
		{ setType: "abs", id: "abs-2h-axe", image: "./public/images/equips/weapon/abs-2h-axe.png", name: "Absolabs Onslaught" },
		{ setType: "abs", id: "abs-1h-hammer", image: "./public/images/equips/weapon/abs-1h-hammer.png", name: "Absolabs Gavel" },
		{ setType: "abs", id: "abs-2h-hammer", image: "./public/images/equips/weapon/abs-2h-hammer.png", name: "Absolabs Truncheon" },
		{ setType: "abs", id: "abs-spear", image: "./public/images/equips/weapon/abs-spear.png", name: "Absolabs Assagai" },
		{ setType: "abs", id: "abs-polearm", image: "./public/images/equips/weapon/abs-polearm.png", name: "Absolabs Lochaber" },
		{ setType: "abs", id: "abs-desperado", image: "./public/images/equips/weapon/abs-desperado.png", name: "Absolabs Blood Seeker" },
		{ setType: "abs", id: "abs-elaha", image: "./public/images/equips/weapon/abs-elaha.png", name: "Absolabs Kusanagi" },
		{ setType: "abs", id: "abs-lapis", image: "./public/images/equips/weapon/abs-lapis.png", name: "Lapis Type 8" },
		{ setType: "abs", id: "abs-katana", image: "./public/images/equips/weapon/abs-katana.png", name: "Absolabs Kogarasumaru" },
		{ setType: "abs", id: "abs-tuner", image: "./public/images/equips/weapon/abs-tuner.png", name: "Absolabs Tuner" },

		{ setType: "faf", id: "faf-1h-sword", image: "./public/images/equips/weapon/faf-1h-sword.png", name: "Fafnir Mystletainn" },
		{ setType: "faf", id: "faf-2h-sword", image: "./public/images/equips/weapon/faf-2h-sword.png", name: "Fafnir Penitencia" },
		{ setType: "faf", id: "faf-1h-axe", image: "./public/images/equips/weapon/faf-1h-axe.png", name: "Fafnir Twin Cleaver" },
		{ setType: "faf", id: "faf-2h-axe", image: "./public/images/equips/weapon/faf-2h-axe.png", name: "Fafnir Battle Cleaver" },
		{ setType: "faf", id: "faf-1h-hammer", image: "./public/images/equips/weapon/faf-1h-hammer.png", name: "Fafnir Golden Hammer" },
		{ setType: "faf", id: "faf-2h-hammer", image: "./public/images/equips/weapon/faf-2h-hammer.png", name: "Fafnir Lightninger" },
		{ setType: "faf", id: "faf-spear", image: "./public/images/equips/weapon/faf-spear.png", name: "Fafnir Bionarc" },
		{ setType: "faf", id: "faf-polearm", image: "./public/images/equips/weapon/faf-polearm.png", name: "Fafnir Moon Glaive" },
		{ setType: "faf", id: "faf-desperado", image: "./public/images/equips/weapon/faf-desperado.png", name: "Fafnir Death Bringer" },
		{ setType: "faf", id: "faf-elaha", image: "./public/images/equips/weapon/faf-elaha.png", name: "Fafnir Gigastein" },
		{ setType: "faf", id: "faf-lapis", image: "./public/images/equips/weapon/faf-lapis.png", name: "Lapis Type 7" },
		{ setType: "faf", id: "faf-katana", image: "./public/images/equips/weapon/faf-katana.png", name: "Fafnir Raven Ring" },
		{ setType: "faf", id: "faf-tuner", image: "./public/images/equips/weapon/faf-tuner.png", name: "Fafnir Forgiveness" },

		{ setType: "none", id: "scarlet-1h-sword", image: "./public/images/equips/weapon/scarlet-1h-sword.png", name: "Scarlet Gladius", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "scarlet-2h-sword", image: "./public/images/equips/weapon/scarlet-2h-sword.png", name: "Scarlet Claymore", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "scarlet-1h-axe", image: "./public/images/equips/weapon/scarlet-1h-axe.png", name: "Scarlet War Cleaver", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "scarlet-2h-axe", image: "./public/images/equips/weapon/scarlet-2h-axe.png", name: "Scarlet Battle Axe", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "scarlet-1h-hammer", image: "./public/images/equips/weapon/scarlet-1h-hammer.png", name: "Scarlet War Hammer", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "scarlet-2h-hammer", image: "./public/images/equips/weapon/scarlet-2h-hammer.png", name: "Scarlet Battle Hammer", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "scarlet-spear", image: "./public/images/equips/weapon/scarlet-spear.png", name: "Scarlet Battle Spear", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "scarlet-polearm", image: "./public/images/equips/weapon/scarlet-polearm.png", name: "Scarlet Halberd", isLuckyItem: true, itemPriority: 100 },
		{ setType: "none", id: "scarlet-desperado", image: "./public/images/equips/weapon/scarlet-desperado.png", name: "Scarlet Death Bringer", isLuckyItem: true, itemPriority: 100 },		
		{ setType: "none", id: "scarlet-katana", image: "./public/images/equips/weapon/scarlet-katana.png", name: "Scarlet Katana", isLuckyItem: true, itemPriority: 100 },
	],
	secondary: [
		{ setType: "none", id: "ruin-force-shield", image: "./public/images/equips/secondary/ruin-force-shield.png", name: "Ruin Force Shield" },
		{ setType: "none", id: "deimos-warrior-shield", image: "./public/images/equips/secondary/deimos-warrior-shield.png", name: "Deimos Warrior Shield" },
		{ setType: "none", id: "pnou-medal", image: "./public/images/equips/secondary/pnou-medal.png", name: "Princess Nou's Medal (Hero)" },
		{ setType: "none", id: "pnou-rosario", image: "./public/images/equips/secondary/pnou-rosario.png", name: "Princess Nou's Rosario (Paladin)" },
		{ setType: "none", id: "pnou-flower-chain", image: "./public/images/equips/secondary/pnou-flower-chain.png", name: "Princess Nou's Flower Chain (Dark Knight)" },
		{ setType: "none", id: "pnou-floral-jewel", image: "./public/images/equips/secondary/pnou-floral-jewel.png", name: "Princess Nou's Floral Jewel (Cygnus Knights)" },
		{ setType: "none", id: "pnou-soul-shield", image: "./public/images/equips/secondary/pnou-soul-shield.png", name: "Princess Nou's Soul Shield (Mihile)" },
		{ setType: "none", id: "pnou-megaton-charges", image: "./public/images/equips/secondary/pnou-megaton-charges.png", name: "Princess Nou's Megaton Charges (Blaster)" },
		{ setType: "none", id: "pnou-demon-aegis", image: "./public/images/equips/secondary/pnou-demon-aegis.png", name: "Princess Nou's Demon Aegis (Demon)" },
		{ setType: "none", id: "pnou-pendulum", image: "./public/images/equips/secondary/pnou-pendulum.png", name: "Princess Nou's Pendulum (Aran)" },
		{ setType: "none", id: "pnou-dragon-essence", image: "./public/images/equips/secondary/pnou-dragon-essence.png", name: "Princess Nou's Dragon Essence (Kaiser)" },
		{ setType: "none", id: "pnou-wakizashi", image: "./public/images/equips/secondary/pnou-wakizashi.png", name: "Princess Nou's Wakizashi (Hayato)" },
		{ setType: "none", id: "pnou-bracelet", image: "./public/images/equips/secondary/pnou-bracelet.png", name: "Princess Nou's Bracelet (Adele)" },
	],
	belt: [
		{ setType: "none", id: "tyrant-belt", image: "./public/images/equips/belt/tyrant-belt.png", name: "Tyrant Hyades Belt" },
	],
	emblem: [
		{ setType: "none", id: "gold-maple-leaf-emblem", image: "./public/images/equips/emblem/gold-maple-leaf-emblem.png", name: "Gold Maple Leaf Emblem (Explorers)" },
		{ setType: "none", id: "gold-cygnus-emblem", image: "./public/images/equips/emblem/gold-cygnus-emblem.png", name: "Gold Cygnus Emblem (Cygnus Knights)" },
		{ setType: "none", id: "gold-resistance-emblem", image: "./public/images/equips/emblem/gold-resistance-emblem.png", name: "Gold Resistance Emblem (Resistance)" },
		{ setType: "none", id: "gold-demon-emblem", image: "./public/images/equips/emblem/gold-demon-emblem.png", name: "Gold Demon Emblem (Demon)" },
		{ setType: "none", id: "gold-aran-emblem", image: "./public/images/equips/emblem/gold-aran-emblem.png", name: "Gold Heroic Emblem (Aran)" },
		{ setType: "none", id: "dragon-emblem", image: "./public/images/equips/emblem/dragon-emblem.png", name: "Dragon Emblem (Kaiser)" },
		{ setType: "none", id: "eternal-time-emblem", image: "./public/images/equips/emblem/eternal-time-emblem.png", name: "Eternal Time Emblem (Zero)" },
		{ setType: "none", id: "gold-crescent-emblem", image: "./public/images/equips/emblem/gold-crescent-emblem.png", name: "Gold Crescent Emblem (Hayato)" },
		{ setType: "none", id: "gold-knight-emblem", image: "./public/images/equips/emblem/gold-knight-emblem.png", name: "Gold Knight Emblem (Adele)" },
	],
}

module.exports = warriorSetItems;